// NeuroCompass-PD v4.2 - Complete Language Support
// Real translations - NOT speech synthesis

const LANGUAGES = {
    en: {
        welcome: 'Welcome to NeuroCompass PD',
        mdsUPDRS: 'MDS-UPDRS Clinical Assessment Suite',
        navigation: 'Navigation',
        dashboard: 'Dashboard',
        pdInfo: 'PD Information',
        patient: 'Patient Profile',
        speech: 'Speech Assessment',
        tremor: 'Tremor Assessment',
        gait: 'Gait Assessment',
        facial: 'Facial Expression',
        questions: 'Questions',
        spiral: 'Spiral Drawing',
        results: 'Results',
        report: 'Report',
        patientProfile: 'Patient Profile',
        screeningTests: 'Screening Tests',
        pdTitle: 'Parkinson\'s Disease Information',
        pdWhat: 'What is Parkinson\'s?',
        pdDescription: 'A progressive neurodegenerative disorder characterized by motor and non-motor symptoms including tremor, bradykinesia, rigidity, and postural instability.',
        updrsTitle: 'MDS-UPDRS Assessment',
        updrsDescription: 'Movement Disorder Society - Unified Parkinson\'s Disease Rating Scale. Clinical gold standard for comprehensive motor and non-motor examination.',
        patientInfo: 'Patient Information',
        firstName: 'First Name',
        lastName: 'Last Name',
        dateOfBirth: 'Date of Birth',
        gender: 'Gender',
        countryCode: 'Country Code',
        phone: 'Phone',
        email: 'Email',
        medicalID: 'Medical ID',
        ageError: 'Must be 18 or older',
        speechAssessment: 'Speech Assessment (MDS-UPDRS Item 3.1)',
        speechDesc: 'Say AAAAA for 6 seconds - Three trials',
        tremorAssessment: 'Tremor Assessment (MDS-UPDRS Item 3.15-3.17)',
        tremorDesc: 'Record tremor from both hands - 10 seconds each',
        gaitAssessment: 'Gait Assessment (MDS-UPDRS Item 3.10-3.12)',
        gaitDesc: 'Walk naturally for 15 seconds - Full video with skeleton tracking',
        facialAssessment: 'Facial Expression (MDS-UPDRS Item 3.1)',
        facialDesc: 'Maintain natural expression for 10 seconds - Full video with face mesh',
        questionsTitle: 'Clinical Questions',
        questionsDesc: 'Answer all clinical questions',
        q1: 'Do you experience slowness of movement?',
        q2: 'Do you experience muscle stiffness or rigidity?',
        q3: 'Do you experience balance or postural instability issues?',
        spiralTitle: 'Spiral Drawing',
        spiralDesc: 'Draw a smooth spiral. Start from center and spiral outward smoothly.',
        reference: 'Reference Spiral',
        yourDrawing: 'Your Drawing',
        jitter: 'Jitter (%)',
        shimmer: 'Shimmer (dB)',
        hnr: 'HNR (dB)',
        f0: 'F0 (Hz)',
        frequency: 'Frequency (Hz)',
        amplitude: 'Amplitude (m/s²)',
        power: 'Power (dB)',
        cadence: 'Cadence (steps/min)',
        strideLength: 'Stride Length (m)',
        speed: 'Speed (m/s)',
        blinkRate: 'Blink Rate (/min)',
        jawOpening: 'Jaw Opening (cm)',
        mouthWidth: 'Mouth Width (cm)',
        tremorIndex: 'Tremor Index',
        pathLength: 'Path Length (px)',
        velocity: 'Velocity (px/step)',
        updrsScore: 'UPDRS Score',
        startingIn: 'Starting in',
        leftHand: 'Left Hand',
        rightHand: 'Right Hand',
        patientSaved: 'Patient profile saved successfully',
        trialComplete: 'Trial complete',
        patientInfoReport: 'Patient Information',
        assessmentSummary: 'Assessment Summary',
        detailedResults: 'Detailed Results'
    },

    hi: {
        welcome: 'NeuroCompass-PD में आपका स्वागत है',
        mdsUPDRS: 'एमडीएस-यूपीडीआरएस नैदानिक मूल्यांकन सूट',
        navigation: 'नेविगेशन',
        dashboard: 'डैशबोर्ड',
        pdInfo: 'पीडी जानकारी',
        patient: 'रोगी प्रोफाइल',
        speech: 'वाणी मूल्यांकन',
        tremor: 'कंपन मूल्यांकन',
        gait: 'गति मूल्यांकन',
        facial: 'चेहरे की अभिव्यक्ति',
        questions: 'प्रश्न',
        spiral: 'सर्पिल चित्र',
        results: 'परिणाम',
        report: 'रिपोर्ट',
        patientProfile: 'रोगी प्रोफाइल',
        screeningTests: 'स्क्रीनिंग परीक्षण',
        pdTitle: 'पार्किंसन रोग की जानकारी',
        pdWhat: 'पार्किंसन क्या है?',
        pdDescription: 'एक प्रगतिशील न्यूरोडीजेनेरेटिव विकार जो कंपन, ब्रैडीकिनेसिया, कठोरता और मुद्रा अस्थिरता सहित मोटर और गैर-मोटर लक्षणों की विशेषता है।',
        updrsTitle: 'एमडीएस-यूपीडीआरएस मूल्यांकन',
        updrsDescription: 'आंदोलन विकार समाज - एकीकृत पार्किंसन रोग रेटिंग स्केल। व्यापक मोटर और गैर-मोटर परीक्षा के लिए नैदानिक स्वर्ण मानक।',
        patientInfo: 'रोगी की जानकारी',
        firstName: 'पहला नाम',
        lastName: 'अंतिम नाम',
        dateOfBirth: 'जन्म की तारीख',
        gender: 'लिंग',
        countryCode: 'देश कोड',
        phone: 'फोन',
        email: 'ईमेल',
        medicalID: 'चिकित्सा आईडी',
        ageError: '18 या अधिक होना चाहिए',
        speechAssessment: 'वाणी मूल्यांकन (एमडीएस-यूपीडीआरएस आइटम 3.1)',
        speechDesc: '6 सेकंड के लिए AAAAA कहें - तीन परीक्षण',
        tremorAssessment: 'कंपन मूल्यांकन (एमडीएस-यूपीडीआरएस आइटम 3.15-3.17)',
        tremorDesc: 'दोनों हाथों से कंपन रिकॉर्ड करें - 10 सेकंड प्रत्येक',
        gaitAssessment: 'गति मूल्यांकन (एमडीएस-यूपीडीआरएस आइटम 3.10-3.12)',
        gaitDesc: 'स्वाभाविक रूप से 15 सेकंड के लिए चलें - कंकाल ट्रैकिंग के साथ पूर्ण वीडियो',
        facialAssessment: 'चेहरे की अभिव्यक्ति (एमडीएस-यूपीडीआरएस आइटम 3.1)',
        facialDesc: '10 सेकंड के लिए प्राकृतिक अभिव्यक्ति बनाए रखें - चेहरे की जाली के साथ पूर्ण वीडियो',
        questionsTitle: 'नैदानिक प्रश्न',
        questionsDesc: 'सभी नैदानिक प्रश्नों के उत्तर दें',
        q1: 'क्या आप आंदोलन की धीमापन का अनुभव करते हैं?',
        q2: 'क्या आप मांसपेशियों की कठोरता या कठोरता का अनुभव करते हैं?',
        q3: 'क्या आप संतुलन या मुद्रा अस्थिरता समस्याओं का अनुभव करते हैं?',
        spiralTitle: 'सर्पिल चित्र',
        spiralDesc: 'एक सुचारु सर्पिल ड्रॉ करें। केंद्र से शुरू करें और सर्पिल को बाहर की ओर ड्रॉ करें।',
        reference: 'संदर्भ सर्पिल',
        yourDrawing: 'आपकी ड्राइंग',
        jitter: 'जिटर (%)',
        shimmer: 'शिमर (डीबी)',
        hnr: 'एचएनआर (डीबी)',
        f0: 'एफ0 (हर्ट्ज)',
        frequency: 'आवृत्ति (हर्ट्ज)',
        amplitude: 'आयाम (मी/एस²)',
        power: 'शक्ति (डीबी)',
        cadence: 'लय (कदम/मिनट)',
        strideLength: 'स्ट्राइड लंबाई (मी)',
        speed: 'गति (मी/एस)',
        blinkRate: 'पलक दर (/मिनट)',
        jawOpening: 'जबड़े की खुलावट (सेमी)',
        mouthWidth: 'मुँह की चौड़ाई (सेमी)',
        tremorIndex: 'कंपन सूचकांक',
        pathLength: 'पथ की लंबाई (पीएक्स)',
        velocity: 'वेग (पीएक्स/कदम)',
        updrsScore: 'यूपीडीआरएस स्कोर',
        startingIn: 'शुरुआत में',
        leftHand: 'बाएं हाथ',
        rightHand: 'दाएं हाथ',
        patientSaved: 'रोगी प्रोफाइल सफलतापूर्वक सहेजा गया',
        trialComplete: 'परीक्षण पूरा',
        patientInfoReport: 'रोगी की जानकारी',
        assessmentSummary: 'मूल्यांकन सारांश',
        detailedResults: 'विस्तृत परिणाम'
    },

    ru: {
        welcome: 'Добро пожаловать в NeuroCompass-PD',
        mdsUPDRS: 'Клиническая шкала оценки БП (MDS-UPDRS)',
        navigation: 'Навигация',
        dashboard: 'Панель управления',
        pdInfo: 'Информация о БП',
        patient: 'Профиль пациента',
        speech: 'Оценка речи',
        tremor: 'Оценка тремора',
        gait: 'Оценка походки',
        facial: 'Мимические выражения',
        questions: 'Вопросы',
        spiral: 'Рисование спирали',
        results: 'Результаты',
        report: 'Отчет',
        patientProfile: 'Профиль пациента',
        screeningTests: 'Тесты скрининга',
        pdTitle: 'Информация о болезни Паркинсона',
        pdWhat: 'Что такое болезнь Паркинсона?',
        pdDescription: 'Прогрессирующее нейродегенеративное заболевание, характеризующееся моторными и немоторными симптомами, включая тремор, брадикинезию, ригидность и постуральную нестабильность.',
        updrsTitle: 'Оценка MDS-UPDRS',
        updrsDescription: 'Унифицированная шкала оценки болезни Паркинсона Общества расстройств движения. Клинический золотой стандарт для комплексного обследования моторных и немоторных функций.',
        patientInfo: 'Информация о пациенте',
        firstName: 'Имя',
        lastName: 'Фамилия',
        dateOfBirth: 'Дата рождения',
        gender: 'Пол',
        countryCode: 'Код страны',
        phone: 'Телефон',
        email: 'Электронная почта',
        medicalID: 'Медицинский идентификатор',
        ageError: 'Должно быть 18 лет или старше',
        speechAssessment: 'Оценка речи (MDS-UPDRS пункт 3.1)',
        speechDesc: 'Скажите AAAAA в течение 6 секунд - три испытания',
        tremorAssessment: 'Оценка тремора (MDS-UPDRS пункты 3.15-3.17)',
        tremorDesc: 'Запишите тремор обеих рук - по 10 секунд каждую',
        gaitAssessment: 'Оценка походки (MDS-UPDRS пункты 3.10-3.12)',
        gaitDesc: 'Ходите естественно в течение 15 секунд - полное видео с отслеживанием скелета',
        facialAssessment: 'Мимические выражения (MDS-UPDRS пункт 3.1)',
        facialDesc: 'Сохраняйте естественное выражение в течение 10 секунд - полное видео с сеткой лица',
        questionsTitle: 'Клинические вопросы',
        questionsDesc: 'Ответьте на все клинические вопросы',
        q1: 'Вы испытываете замедленность движений?',
        q2: 'Вы испытываете мышечную скованность или ригидность?',
        q3: 'Вы испытываете проблемы с равновесием или нестабильностью постуры?',
        spiralTitle: 'Рисование спирали',
        spiralDesc: 'Нарисуйте плавную спираль. Начните с центра и спирально расширяйте наружу.',
        reference: 'Справочная спираль',
        yourDrawing: 'Ваш рисунок',
        jitter: 'Джиттер (%)',
        shimmer: 'Шиммер (дБ)',
        hnr: 'ХНР (дБ)',
        f0: 'Ф0 (Гц)',
        frequency: 'Частота (Гц)',
        amplitude: 'Амплитуда (м/с²)',
        power: 'Мощность (дБ)',
        cadence: 'Темп (шагов/мин)',
        strideLength: 'Длина шага (м)',
        speed: 'Скорость (м/с)',
        blinkRate: 'Частота моргания (/мин)',
        jawOpening: 'Раскрытие челюсти (см)',
        mouthWidth: 'Ширина рта (см)',
        tremorIndex: 'Индекс тремора',
        pathLength: 'Длина пути (px)',
        velocity: 'Скорость (px/шаг)',
        updrsScore: 'Оценка UPDRS',
        startingIn: 'Начинается через',
        leftHand: 'Левая рука',
        rightHand: 'Правая рука',
        patientSaved: 'Профиль пациента успешно сохранен',
        trialComplete: 'Испытание завершено',
        patientInfoReport: 'Информация о пациенте',
        assessmentSummary: 'Резюме оценки',
        detailedResults: 'Подробные результаты'
    }
};

// Get translation
function t(key) {
    const text = LANGUAGES[STATE.language]?.[key];
    return text || LANGUAGES['en']?.[key] || key;
}