const LANGUAGES = {
    en: {
        welcome: 'Welcome to NeuroCompass-PD',
        dashboard: 'Dashboard',
        patientProfile: 'Patient Profile',
        tests: 'Tests',
        report: 'Report',
        startTests: 'Start Tests',
        complete: 'Complete',
        results: 'Results',
        required: 'Required',
        speech: 'Speech Assessment',
        tremor: 'Tremor Assessment',
        gait: 'Gait Assessment',
        facial: 'Facial Expression',
        questions: 'Questions',
        spiral: 'Spiral Drawing',
        fillPatient: 'Fill Patient Information',
        patientInfo: 'Patient Information',
        firstName: 'First Name',
        lastName: 'Last Name',
        dob: 'Date of Birth',
        gender: 'Gender',
        country: 'Country Code',
        phone: 'Phone',
        email: 'Email',
        medicalId: 'Medical ID',
        save: 'Save & Unlock Tests',
        start: 'Start',
        next: 'Next',
        cancel: 'Cancel',
        clear: 'Clear',
        download: 'Download PDF',
        back: 'Back',
        speechDesc: 'Say "AAAAA" for 6 seconds',
        tremorDesc: 'Record tremor from both hands',
        gaitDesc: 'Walk naturally for 15 seconds',
        facialDesc: 'Maintain natural expression for 10 seconds',
        spiralDesc: 'Draw a smooth spiral. Start from center.',
        questionsDesc: 'Answer all questions',
        selectHand: 'SELECT HAND',
        leftHand: 'Left Hand',
        rightHand: 'Right Hand',
        reference: 'Reference',
        yourDrawing: 'Your Drawing',
        jitter: 'Jitter',
        shimmer: 'Shimmer',
        hnr: 'HNR',
        f0: 'F0',
        frequency: 'Frequency',
        amplitude: 'Amplitude',
        power: 'Power',
        cadence: 'Cadence',
        strideLength: 'Stride Length',
        speed: 'Speed',
        blinkRate: 'Blink Rate',
        jawOpening: 'Jaw Opening',
        mouthWidth: 'Mouth Width',
        tremorIndex: 'Tremor Index',
        pathLength: 'Path Length',
        velocity: 'Velocity'
    },
    hi: {
        welcome: 'NeuroCompass-PD में आपका स्वागत है',
        dashboard: 'डैशबोर्ड',
        patientProfile: 'रोगी प्रोफाइल',
        tests: 'परीक्षण',
        report: 'रिपोर्ट',
        startTests: 'परीक्षण शुरू करें',
        complete: 'पूर्ण',
        results: 'परिणाम',
        required: 'आवश्यक',
        speech: 'वाणी मूल्यांकन',
        tremor: 'कंपन मूल्यांकन',
        gait: 'गति मूल्यांकन',
        facial: 'चेहरे की अभिव्यक्ति',
        questions: 'प्रश्न',
        spiral: 'सर्पिल चित्र',
        fillPatient: 'रोगी की जानकारी भरें',
        patientInfo: 'रोगी की जानकारी',
        firstName: 'पहला नाम',
        lastName: 'अंतिम नाम',
        dob: 'जन्म की तारीख',
        gender: 'लिंग',
        country: 'देश कोड',
        phone: 'फोन',
        email: 'ईमेल',
        medicalId: 'चिकित्सा आईडी',
        save: 'सहेजें और परीक्षण अनलॉक करें',
        start: 'शुरू करें',
        next: 'अगला',
        cancel: 'रद्द करें',
        clear: 'स्पष्ट करें',
        download: 'पीडीएफ डाउनलोड करें',
        back: 'वापस',
        speechDesc: '6 सेकंड के लिए "AAAAA" कहें',
        tremorDesc: 'दोनों हाथों से कंपन रिकॉर्ड करें',
        gaitDesc: 'स्वाभाविक रूप से 15 सेकंड के लिए चलें',
        facialDesc: '10 सेकंड के लिए प्राकृतिक अभिव्यक्ति बनाए रखें',
        spiralDesc: 'एक सुचारु सर्पिल ड्रॉ करें। केंद्र से शुरू करें।',
        questionsDesc: 'सभी प्रश्नों का उत्तर दें',
        selectHand: 'हाथ चुनें',
        leftHand: 'बाएं हाथ',
        rightHand: 'दाएं हाथ',
        reference: 'संदर्भ',
        yourDrawing: 'आपकी ड्राइंग',
        jitter: 'जिटर',
        shimmer: 'शिमर',
        hnr: 'एचएनआर',
        f0: 'एफ0',
        frequency: 'आवृत्ति',
        amplitude: 'आयाम',
        power: 'शक्ति',
        cadence: 'लय',
        strideLength: 'स्ट्राइड लंबाई',
        speed: 'गति',
        blinkRate: 'पलक की दर',
        jawOpening: 'जबड़े की खुलावट',
        mouthWidth: 'मुँह की चौड़ाई',
        tremorIndex: 'कंपन सूचकांक',
        pathLength: 'पथ की लंबाई',
        velocity: 'वेग'
    },
    ru: {
        welcome: 'Добро пожаловать в NeuroCompass-PD',
        dashboard: 'Панель управления',
        patientProfile: 'Профиль пациента',
        tests: 'Тесты',
        report: 'Отчет',
        startTests: 'Начать тесты',
        complete: 'Завершить',
        results: 'Результаты',
        required: 'Требуется',
        speech: 'Оценка речи',
        tremor: 'Оценка тремора',
        gait: 'Оценка походки',
        facial: 'Мимические выражения',
        questions: 'Вопросы',
        spiral: 'Рисование спирали',
        fillPatient: 'Заполните информацию пациента',
        patientInfo: 'Информация о пациенте',
        firstName: 'Имя',
        lastName: 'Фамилия',
        dob: 'Дата рождения',
        gender: 'Пол',
        country: 'Код страны',
        phone: 'Телефон',
        email: 'Электронная почта',
        medicalId: 'Медицинский идентификатор',
        save: 'Сохранить и разблокировать тесты',
        start: 'Начать',
        next: 'Далее',
        cancel: 'Отмена',
        clear: 'Очистить',
        download: 'Загрузить PDF',
        back: 'Назад',
        speechDesc: 'Говорите "AAAAA" в течение 6 секунд',
        tremorDesc: 'Записывайте тремор обеих рук',
        gaitDesc: 'Ходите естественно в течение 15 секунд',
        facialDesc: 'Сохраняйте естественное выражение в течение 10 секунд',
        spiralDesc: 'Нарисуйте плавную спираль. Начните с центра.',
        questionsDesc: 'Ответьте на все вопросы',
        selectHand: 'ВЫБРАТЬ РУКУ',
        leftHand: 'Левая рука',
        rightHand: 'Правая рука',
        reference: 'Ссылка',
        yourDrawing: 'Ваш рисунок',
        jitter: 'Джиттер',
        shimmer: 'Шиммер',
        hnr: 'ХНР',
        f0: 'Ф0',
        frequency: 'Частота',
        amplitude: 'Амплитуда',
        power: 'Мощность',
        cadence: 'Темп',
        strideLength: 'Длина шага',
        speed: 'Скорость',
        blinkRate: 'Частота моргания',
        jawOpening: 'Раскрытие челюсти',
        mouthWidth: 'Ширина рта',
        tremorIndex: 'Индекс тремора',
        pathLength: 'Длина пути',
        velocity: 'Скорость'
    }
};