// NeuroCompass-PD v6.0 - Complete Multi-Language Support
// ALL TRANSLATIONS FOR: English, Hindi, Russian, Kyrgyz, Kazakh

let currentLanguage = localStorage.getItem('language') || 'en';

const LANGUAGES = {
    en: { // ENGLISH
        appTitle: 'NeuroCompass-PD',
        version: 'v6.0',
        subtitle: 'Clinical Assessment Platform',
        
        // Navbar
        dashboard: 'Dashboard',
        navDashboard: 'Dashboard',
        navInfo: 'PD Information',
        navPatient: 'Patient Profile',
        navVoice: 'Speech Assessment',
        navTremor: 'Tremor Assessment',
        navGait: 'Gait Assessment',
        navFacial: 'Facial Expression',
        navQuestions: 'Questions',
        navSpiral: 'Spiral Drawing',
        navResults: 'Results',
        navReport: 'Report',
        navigationTitle: 'Navigation',
        disclaimerText: 'Research prototype only',
        
        // Dashboard
        dashboardTitle: 'Dashboard',
        dashboardDesc: 'Clinical Assessment Overview',
        noPatientText: 'No patient information',
        voiceBoxTitle: 'Speech',
        tremorBoxTitle: 'Tremor',
        gaitBoxTitle: 'Gait',
        facialBoxTitle: 'Facial',
        questionsBoxTitle: 'Questions',
        spiralBoxTitle: 'Spiral',
        voiceStatus: 'Not started',
        tremorStatus: 'Not started',
        gaitStatus: 'Not started',
        facialStatus: 'Not started',
        questionsStatus: 'Not started',
        spiralStatus: 'Not started',
        startBtn: 'Start Assessment',
        
        // Patient Profile
        patientTitle: 'Patient Profile',
        patientDesc: 'Complete demographic information',
        labelFirstName: 'First Name',
        labelLastName: 'Last Name',
        labelDOB: 'Date of Birth',
        labelGender: 'Gender',
        labelCountry: 'Country',
        labelPhone: 'Phone',
        labelEmail: 'Email',
        labelMedicalId: 'Medical Record ID',
        optMale: 'Male',
        optFemale: 'Female',
        optOther: 'Other',
        savePatientBtn: 'Save Profile',
        patientSaved: 'Patient profile saved successfully!',
        
        // Info Page
        infoTitle: 'Parkinson\'s Disease Information',
        infoSubtitle: 'Clinical Background & MDS-UPDRS Part III',
        whatIsPDTitle: 'What is Parkinson\'s Disease?',
        whatIsPDText: 'Progressive neurodegenerative disorder characterized by tremor, bradykinesia, rigidity, and postural instability.',
        updrsTitle: 'MDS-UPDRS Part III Scoring',
        scoreHeader: 'Score',
        severityHeader: 'Severity',
        sev0: 'Normal',
        sev1: 'Slight',
        sev2: 'Mild',
        sev3: 'Moderate',
        sev4: 'Severe',
        
        // Voice Test
        voiceTitle: 'Speech Assessment',
        voiceDesc: 'Record 3 trials of sustained "AAAAA" (6 seconds each)',
        voiceInstructions: 'You will record 3 trials. Click below to start.',
        startVoiceBtn: '🎤 Start Recording',
        countdownText: 'Starting in...',
        recordingText: 'Recording...',
        trialResultsTitle: 'Trial Results',
        jitterLabel: 'Jitter (%)',
        shimmerLabel: 'Shimmer (dB)',
        hnrLabel: 'HNR (dB)',
        f0Label: 'F0 (Hz)',
        voiceNextBtn: '🎤 Next Trial',
        voiceCompleteBtn: '✓ Complete Test',
        
        // Tremor Test
        tremorTitle: 'Tremor Assessment',
        tremorDesc: 'Hold device steady for 10 seconds',
        tremorInstructions: 'Select which hand to test:',
        leftHandBtn: '👈 Left Hand',
        rightHandBtn: '👉 Right Hand',
        tremorCountText: 'Starting in...',
        tremorRecText: 'Recording...',
        tremorMetricsTitle: 'Tremor Metrics',
        frequencyLabel: 'Frequency (Hz)',
        amplitudeLabel: 'Amplitude (m/s²)',
        powerLabel: 'Power (dB)',
        tremorCompleteBtn: '✓ Complete Test',
        
        // Gait Test
        gaitTitle: 'Gait Assessment',
        gaitDesc: 'Camera-based gait analysis (15 seconds)',
        gaitInstructions: 'Position yourself in frame and click to start.',
        startGaitBtn: '📹 Start Camera',
        gaitRecText: 'Analyzing...',
        cadenceLabel: 'Cadence (steps/min)',
        strideLabel: 'Stride Length (m)',
        speedLabel: 'Speed (m/s)',
        gaitCompleteBtn: '✓ Complete Test',
        greenSkeleton: 'GREEN SKELETON VISIBLE',
        
        // Facial Test
        facialTitle: 'Facial Expression Assessment',
        facialDesc: 'Camera-based facial analysis (10 seconds)',
        facialInstructions: 'Position your face in frame and click to start.',
        startFacialBtn: '📹 Start Camera',
        facialRecText: 'Analyzing...',
        blinkLabel: 'Blink Rate (/min)',
        jawLabel: 'Jaw Opening (cm)',
        mouthLabel: 'Mouth Width (cm)',
        facialCompleteBtn: '✓ Complete Test',
        magentaMesh: 'MAGENTA FACE MESH VISIBLE',
        
        // Questions
        questionsTitle: 'Questions Assessment',
        q1Label: '1. Do you experience slowness of movement (bradykinesia)?',
        q2Label: '2. Do you have stiffness/rigidity in arms or legs?',
        q3Label: '3. Do you have balance issues or near falls?',
        q1No: 'No',
        q1Sometimes: 'Sometimes',
        q1Often: 'Often',
        q1Always: 'Always',
        q2No: 'No',
        q2Sometimes: 'Sometimes',
        q2Often: 'Often',
        q2Always: 'Always',
        q3No: 'No',
        q3Sometimes: 'Sometimes',
        q3Often: 'Often',
        q3Always: 'Always',
        submitQuestionsBtn: 'Save Answers',
        
        // Spiral
        spiralTitle: 'Spiral Drawing Test',
        spiralDesc: 'Draw a smooth spiral using your finger/stylus',
        refSpiralTitle: 'Reference',
        yourSpiralTitle: 'Your Drawing',
        clearBtn: 'Clear',
        tremorIndexLabel: 'Tremor Index',
        pathLengthLabel: 'Path Length (px)',
        velocityLabel: 'Velocity (px/s)',
        calcSpiralBtn: 'Calculate Metrics',
        spiralCompleteBtn: '✓ Complete Test',
        
        // Results
        resultsTitle: 'Assessment Results',
        resultsDesc: 'Complete MDS-UPDRS Summary',
        domainHeader: 'Domain',
        scoreHeader2: 'Score (0-4)',
        severityHeader2: 'Severity',
        generateReportBtn: '📄 Generate Report',
        
        // Report
        reportTitle: 'Clinical Report',
        patientInfoTitle: 'Patient Information',
        assessmentSummaryTitle: 'Assessment Summary',
        rptNameLabel: 'Name:',
        rptAgeLabel: 'Age:',
        rptGenderLabel: 'Gender:',
        rptCountryLabel: 'Country:',
        rptEmailLabel: 'Email:',
        rptVoiceSevLabel: 'Speech Severity:',
        rptTremorSevLabel: 'Tremor Severity:',
        rptGaitSevLabel: 'Gait Severity:',
        rptFacialSevLabel: 'Facial Severity:',
        rptCogSevLabel: 'Cognitive Severity:',
        rptCoordSevLabel: 'Coordination Severity:',
        disclaimerNote: 'Clinical Disclaimer: This is a research screening tool. Always consult with a qualified clinician for diagnosis and treatment decisions.',
        downloadPDFBtn: '📥 Download PDF Report',
        
        // Countries
        countries: {
            IN: 'India',
            US: 'United States',
            UK: 'United Kingdom',
            CA: 'Canada',
            AU: 'Australia',
            DE: 'Germany',
            FR: 'France',
            JP: 'Japan',
            CN: 'China',
            BR: 'Brazil',
            RU: 'Russia',
            KG: 'Kyrgyzstan',
            KZ: 'Kazakhstan',
        }
    },

    hi: { // HINDI (हिन्दी)
        appTitle: 'न्यूरोकम्पास-पीडी',
        version: 'v6.0',
        subtitle: 'क्लिनिकल मूल्यांकन प्लेटफॉर्म',
        
        dashboard: 'डैशबोर्ड',
        navDashboard: 'डैशबोर्ड',
        navInfo: 'पीडी जानकारी',
        navPatient: 'रोगी प्रोफाइल',
        navVoice: 'भाषण मूल्यांकन',
        navTremor: 'कंपन मूल्यांकन',
        navGait: 'चाल मूल्यांकन',
        navFacial: 'चेहरे की अभिव्यक्ति',
        navQuestions: 'प्रश्न',
        navSpiral: 'सर्पिल ड्राइंग',
        navResults: 'परिणाम',
        navReport: 'रिपोर्ट',
        navigationTitle: 'नेविगेशन',
        disclaimerText: 'केवल अनुसंधान प्रोटोटाइप',
        
        dashboardTitle: 'डैशबोर्ड',
        dashboardDesc: 'क्लिनिकल मूल्यांकन सारांश',
        noPatientText: 'कोई रोगी जानकारी नहीं',
        voiceBoxTitle: 'भाषण',
        tremorBoxTitle: 'कंपन',
        gaitBoxTitle: 'चाल',
        facialBoxTitle: 'चेहरा',
        questionsBoxTitle: 'प्रश्न',
        spiralBoxTitle: 'सर्पिल',
        voiceStatus: 'शुरू नहीं',
        tremorStatus: 'शुरू नहीं',
        gaitStatus: 'शुरू नहीं',
        facialStatus: 'शुरू नहीं',
        questionsStatus: 'शुरू नहीं',
        spiralStatus: 'शुरू नहीं',
        startBtn: 'मूल्यांकन शुरू करें',
        
        patientTitle: 'रोगी प्रोफाइल',
        patientDesc: 'पूर्ण जनसांख्यिकीय जानकारी',
        labelFirstName: 'पहला नाम',
        labelLastName: 'अंतिम नाम',
        labelDOB: 'जन्म तारीख',
        labelGender: 'लिंग',
        labelCountry: 'देश',
        labelPhone: 'फोन',
        labelEmail: 'ईमेल',
        labelMedicalId: 'चिकित्सा रिकॉर्ड आईडी',
        optMale: 'पुरुष',
        optFemale: 'महिला',
        optOther: 'अन्य',
        savePatientBtn: 'प्रोफाइल सहेजें',
        patientSaved: 'रोगी प्रोफाइल सफलतापूर्वक सहेजा गया!',
        
        infoTitle: 'पार्किंसन रोग जानकारी',
        infoSubtitle: 'क्लिनिकल पृष्ठभूमि और एमडीएस-यूपीडीआरएस भाग III',
        whatIsPDTitle: 'पार्किंसन रोग क्या है?',
        whatIsPDText: 'कंपन, ब्रैडिकिनेसिया, कठोरता और मुद्रा संबंधी अस्थिरता की विशेषता वाला प्रगतिशील न्यूरोडीजेनेरेटिव विकार।',
        updrsTitle: 'एमडीएस-यूपीडीआरएस भाग III स्कोरिंग',
        scoreHeader: 'स्कोर',
        severityHeader: 'गंभीरता',
        sev0: 'सामान्य',
        sev1: 'हल्का',
        sev2: 'मध्यम',
        sev3: 'मध्यम',
        sev4: 'गंभीर',
        
        voiceTitle: 'भाषण मूल्यांकन',
        voiceDesc: '3 परीक्षणों को रिकॉर्ड करें (6 सेकंड प्रत्येक)',
        voiceInstructions: 'आप 3 परीक्षण रिकॉर्ड करेंगे। शुरू करने के लिए नीचे क्लिक करें।',
        startVoiceBtn: '🎤 रिकॉर्डिंग शुरू करें',
        countdownText: 'शुरू हो रहा है...',
        recordingText: 'रिकॉर्ड हो रहा है...',
        trialResultsTitle: 'परीक्षण परिणाम',
        jitterLabel: 'जिटर (%)',
        shimmerLabel: 'शिमर (डीबी)',
        hnrLabel: 'एचएनआर (डीबी)',
        f0Label: 'एफ0 (हर्ट्ज)',
        voiceNextBtn: '🎤 अगला परीक्षण',
        voiceCompleteBtn: '✓ परीक्षण पूर्ण करें',
        
        tremorTitle: 'कंपन मूल्यांकन',
        tremorDesc: 'डिवाइस को 10 सेकंड तक स्थिर रखें',
        tremorInstructions: 'परीक्षण के लिए कौन सा हाथ चुनें:',
        leftHandBtn: '👈 बाया हाथ',
        rightHandBtn: '👉 दाया हाथ',
        tremorCountText: 'शुरू हो रहा है...',
        tremorRecText: 'रिकॉर्ड हो रहा है...',
        tremorMetricsTitle: 'कंपन मेट्रिक्स',
        frequencyLabel: 'आवृत्ति (हर्ट्ज)',
        amplitudeLabel: 'आयाम (एम/एस²)',
        powerLabel: 'शक्ति (डीबी)',
        tremorCompleteBtn: '✓ परीक्षण पूर्ण करें',
        
        gaitTitle: 'चाल मूल्यांकन',
        gaitDesc: 'कैमरा-आधारित चाल विश्लेषण (15 सेकंड)',
        gaitInstructions: 'अपने आप को फ्रेम में रखें और शुरू करने के लिए क्लिक करें।',
        startGaitBtn: '📹 कैमरा शुरू करें',
        gaitRecText: 'विश्लेषण हो रहा है...',
        cadenceLabel: 'कैडेंस (कदम/मिनट)',
        strideLabel: 'स्ट्राइड लंबाई (मीटर)',
        speedLabel: 'गति (मीटर/सेकंड)',
        gaitCompleteBtn: '✓ परीक्षण पूर्ण करें',
        greenSkeleton: 'हरा कंकाल दिखाई दे रहा है',
        
        facialTitle: 'चेहरे की अभिव्यक्ति का मूल्यांकन',
        facialDesc: 'कैमरा-आधारित चेहरे का विश्लेषण (10 सेकंड)',
        facialInstructions: 'अपने चेहरे को फ्रेम में रखें और शुरू करने के लिए क्लिक करें।',
        startFacialBtn: '📹 कैमरा शुरू करें',
        facialRecText: 'विश्लेषण हो रहा है...',
        blinkLabel: 'पलक झपकने की दर (/मिनट)',
        jawLabel: 'जबड़ा खुलना (सेमी)',
        mouthLabel: 'मुंह की चौड़ाई (सेमी)',
        facialCompleteBtn: '✓ परीक्षण पूर्ण करें',
        magentaMesh: 'मैजेंटा चेहरा मेश दिखाई दे रहा है',
        
        questionsTitle: 'प्रश्न मूल्यांकन',
        q1Label: '1. क्या आप आंदोलन की सुस्ती (ब्रैडिकिनेसिया) का अनुभव करते हैं?',
        q2Label: '2. क्या आपके हाथों या पैरों में अकड़न/कठोरता है?',
        q3Label: '3. क्या आपको संतुलन की समस्या या गिरने का खतरा है?',
        q1No: 'नहीं',
        q1Sometimes: 'कभी-कभी',
        q1Often: 'अक्सर',
        q1Always: 'हमेशा',
        q2No: 'नहीं',
        q2Sometimes: 'कभी-कभी',
        q2Often: 'अक्सर',
        q2Always: 'हमेशा',
        q3No: 'नहीं',
        q3Sometimes: 'कभी-कभी',
        q3Often: 'अक्सर',
        q3Always: 'हमेशा',
        submitQuestionsBtn: 'उत्तर सहेजें',
        
        spiralTitle: 'सर्पिल ड्राइंग परीक्षण',
        spiralDesc: 'अपनी उंगली/स्टाइलस का उपयोग करके एक चिकनी सर्पिल ड्राइंग करें',
        refSpiralTitle: 'संदर्भ',
        yourSpiralTitle: 'आपकी ड्राइंग',
        clearBtn: 'साफ करें',
        tremorIndexLabel: 'कंपन सूचकांक',
        pathLengthLabel: 'पथ लंबाई (पिक्सल)',
        velocityLabel: 'वेग (पिक्सल/सेकंड)',
        calcSpiralBtn: 'मेट्रिक्स की गणना करें',
        spiralCompleteBtn: '✓ परीक्षण पूर्ण करें',
        
        resultsTitle: 'मूल्यांकन परिणाम',
        resultsDesc: 'संपूर्ण एमडीएस-यूपीडीआरएस सारांश',
        domainHeader: 'डोमेन',
        scoreHeader2: 'स्कोर (0-4)',
        severityHeader2: 'गंभीरता',
        generateReportBtn: '📄 रिपोर्ट जेनरेट करें',
        
        reportTitle: 'क्लिनिकल रिपोर्ट',
        patientInfoTitle: 'रोगी की जानकारी',
        assessmentSummaryTitle: 'मूल्यांकन सारांश',
        rptNameLabel: 'नाम:',
        rptAgeLabel: 'आयु:',
        rptGenderLabel: 'लिंग:',
        rptCountryLabel: 'देश:',
        rptEmailLabel: 'ईमेल:',
        rptVoiceSevLabel: 'भाषण गंभीरता:',
        rptTremorSevLabel: 'कंपन गंभीरता:',
        rptGaitSevLabel: 'चाल गंभीरता:',
        rptFacialSevLabel: 'चेहरे की गंभीरता:',
        rptCogSevLabel: 'संज्ञानात्मक गंभीरता:',
        rptCoordSevLabel: 'समन्वय गंभीरता:',
        disclaimerNote: 'क्लिनिकल अस्वीकरण: यह एक अनुसंधान स्क्रीनिंग टूल है। निदान और उपचार निर्णयों के लिए हमेशा एक योग्य चिकित्सक से परामर्श लें।',
        downloadPDFBtn: '📥 पीडीएफ रिपोर्ट डाउनलोड करें',
        
        countries: {
            IN: 'भारत',
            US: 'संयुक्त राज्य',
            UK: 'यूनाइटेड किंगडम',
            CA: 'कनाडा',
            AU: 'ऑस्ट्रेलिया',
            DE: 'जर्मनी',
            FR: 'फ्रांस',
            JP: 'जापान',
            CN: 'चीन',
            BR: 'ब्राजील',
            RU: 'रूस',
            KG: 'किर्गिज़स्तान',
            KZ: 'कजाकिस्तान',
        }
    },

    ru: { // RUSSIAN (Русский)
        appTitle: 'НейроКомпас-ПД',
        version: 'v6.0',
        subtitle: 'Клиническая платформа оценки',
        
        dashboard: 'Панель управления',
        navDashboard: 'Панель управления',
        navInfo: 'Информация о БП',
        navPatient: 'Профиль пациента',
        navVoice: 'Оценка речи',
        navTremor: 'Оценка тремора',
        navGait: 'Оценка ходьбы',
        navFacial: 'Выражение лица',
        navQuestions: 'Вопросы',
        navSpiral: 'Спиральный рисунок',
        navResults: 'Результаты',
        navReport: 'Отчет',
        navigationTitle: 'Навигация',
        disclaimerText: 'Только исследовательский прототип',
        
        dashboardTitle: 'Панель управления',
        dashboardDesc: 'Обзор клинической оценки',
        noPatientText: 'Нет информации о пациенте',
        voiceBoxTitle: 'Речь',
        tremorBoxTitle: 'Тремор',
        gaitBoxTitle: 'Ходьба',
        facialBoxTitle: 'Лицо',
        questionsBoxTitle: 'Вопросы',
        spiralBoxTitle: 'Спираль',
        voiceStatus: 'Не начато',
        tremorStatus: 'Не начато',
        gaitStatus: 'Не начато',
        facialStatus: 'Не начато',
        questionsStatus: 'Не начато',
        spiralStatus: 'Не начато',
        startBtn: 'Начать оценку',
        
        patientTitle: 'Профиль пациента',
        patientDesc: 'Полная демографическая информация',
        labelFirstName: 'Имя',
        labelLastName: 'Фамилия',
        labelDOB: 'Дата рождения',
        labelGender: 'Пол',
        labelCountry: 'Страна',
        labelPhone: 'Телефон',
        labelEmail: 'Электронная почта',
        labelMedicalId: 'Идентификатор медицинской карты',
        optMale: 'Мужской',
        optFemale: 'Женский',
        optOther: 'Другое',
        savePatientBtn: 'Сохранить профиль',
        patientSaved: 'Профиль пациента успешно сохранен!',
        
        infoTitle: 'Информация о болезни Паркинсона',
        infoSubtitle: 'Клинический справочник и MDS-UPDRS часть III',
        whatIsPDTitle: 'Что такое болезнь Паркинсона?',
        whatIsPDText: 'Прогрессирующее нейродегенеративное заболевание, характеризующееся тремором, брадикинезией, ригидностью и постуральной нестабильностью.',
        updrsTitle: 'Оценка MDS-UPDRS часть III',
        scoreHeader: 'Оценка',
        severityHeader: 'Тяжесть',
        sev0: 'Норма',
        sev1: 'Легкая',
        sev2: 'Мягкая',
        sev3: 'Умеренная',
        sev4: 'Тяжелая',
        
        voiceTitle: 'Оценка речи',
        voiceDesc: 'Запишите 3 попытки по 6 секунд каждая',
        voiceInstructions: 'Вы запишете 3 попытки. Нажмите ниже, чтобы начать.',
        startVoiceBtn: '🎤 Начать запись',
        countdownText: 'Начинаю через...',
        recordingText: 'Запись...',
        trialResultsTitle: 'Результаты испытания',
        jitterLabel: 'Jitter (%)',
        shimmerLabel: 'Shimmer (дБ)',
        hnrLabel: 'HNR (дБ)',
        f0Label: 'F0 (Гц)',
        voiceNextBtn: '🎤 Следующая попытка',
        voiceCompleteBtn: '✓ Завершить тест',
        
        tremorTitle: 'Оценка тремора',
        tremorDesc: 'Держите устройство неподвижно 10 секунд',
        tremorInstructions: 'Выберите, какую руку тестировать:',
        leftHandBtn: '👈 Левая рука',
        rightHandBtn: '👉 Правая рука',
        tremorCountText: 'Начинаю через...',
        tremorRecText: 'Запись...',
        tremorMetricsTitle: 'Метрики тремора',
        frequencyLabel: 'Частота (Гц)',
        amplitudeLabel: 'Амплитуда (м/с²)',
        powerLabel: 'Мощность (дБ)',
        tremorCompleteBtn: '✓ Завершить тест',
        
        gaitTitle: 'Оценка ходьбы',
        gaitDesc: 'Анализ ходьбы на основе камеры (15 секунд)',
        gaitInstructions: 'Встаньте в кадр и нажмите, чтобы начать.',
        startGaitBtn: '📹 Начать камеру',
        gaitRecText: 'Анализирую...',
        cadenceLabel: 'Темп (шаги/мин)',
        strideLabel: 'Длина шага (м)',
        speedLabel: 'Скорость (м/с)',
        gaitCompleteBtn: '✓ Завершить тест',
        greenSkeleton: 'ЗЕЛЕНЫЙ СКЕЛЕТ ВИДЕН',
        
        facialTitle: 'Оценка выражения лица',
        facialDesc: 'Анализ лица на основе камеры (10 секунд)',
        facialInstructions: 'Поместите свое лицо в кадр и нажмите, чтобы начать.',
        startFacialBtn: '📹 Начать камеру',
        facialRecText: 'Анализирую...',
        blinkLabel: 'Частота мигания (/мин)',
        jawLabel: 'Открытие челюсти (см)',
        mouthLabel: 'Ширина рта (см)',
        facialCompleteBtn: '✓ Завершить тест',
        magentaMesh: 'ПУРПУРНАЯ СЕТКА ЛИЦА ВИДНА',
        
        questionsTitle: 'Оценка вопросов',
        q1Label: '1. Испытываете ли вы замедленность движений (брадикинезию)?',
        q2Label: '2. Есть ли у вас жесткость/ригидность рук или ног?',
        q3Label: '3. Есть ли у вас проблемы с равновесием или близкие падения?',
        q1No: 'Нет',
        q1Sometimes: 'Иногда',
        q1Often: 'Часто',
        q1Always: 'Всегда',
        q2No: 'Нет',
        q2Sometimes: 'Иногда',
        q2Often: 'Часто',
        q2Always: 'Всегда',
        q3No: 'Нет',
        q3Sometimes: 'Иногда',
        q3Often: 'Часто',
        q3Always: 'Всегда',
        submitQuestionsBtn: 'Сохранить ответы',
        
        spiralTitle: 'Тест рисования спирали',
        spiralDesc: 'Нарисуйте гладкую спираль пальцем/стилусом',
        refSpiralTitle: 'Ссылка',
        yourSpiralTitle: 'Ваш рисунок',
        clearBtn: 'Очистить',
        tremorIndexLabel: 'Индекс тремора',
        pathLengthLabel: 'Длина пути (px)',
        velocityLabel: 'Скорость (px/s)',
        calcSpiralBtn: 'Вычислить метрики',
        spiralCompleteBtn: '✓ Завершить тест',
        
        resultsTitle: 'Результаты оценки',
        resultsDesc: 'Полная сводка MDS-UPDRS',
        domainHeader: 'Домен',
        scoreHeader2: 'Оценка (0-4)',
        severityHeader2: 'Тяжесть',
        generateReportBtn: '📄 Создать отчет',
        
        reportTitle: 'Клинический отчет',
        patientInfoTitle: 'Информация о пациенте',
        assessmentSummaryTitle: 'Сводка оценки',
        rptNameLabel: 'Имя:',
        rptAgeLabel: 'Возраст:',
        rptGenderLabel: 'Пол:',
        rptCountryLabel: 'Страна:',
        rptEmailLabel: 'Электронная почта:',
        rptVoiceSevLabel: 'Тяжесть речи:',
        rptTremorSevLabel: 'Тяжесть тремора:',
        rptGaitSevLabel: 'Тяжесть ходьбы:',
        rptFacialSevLabel: 'Тяжесть лица:',
        rptCogSevLabel: 'Когнитивная тяжесть:',
        rptCoordSevLabel: 'Тяжесть координации:',
        disclaimerNote: 'Клиническое заявление об отказе от ответственности: это исследовательский инструмент скрининга. Всегда проконсультируйтесь с квалифицированным клиницистом для диагностики и принятия решений о лечении.',
        downloadPDFBtn: '📥 Загрузить PDF отчет',
        
        countries: {
            IN: 'Индия',
            US: 'Соединённые Штаты',
            UK: 'Соединённое Королевство',
            CA: 'Канада',
            AU: 'Австралия',
            DE: 'Германия',
            FR: 'Франция',
            JP: 'Япония',
            CN: 'Китай',
            BR: 'Бразилия',
            RU: 'Россия',
            KG: 'Киргизия',
            KZ: 'Казахстан',
        }
    },

    kg: { // KYRGYZ (Кыргызча)
        appTitle: 'НейроКомпас-ПД',
        version: 'v6.0',
        subtitle: 'Клиникалык баалоо платформасы',
        
        dashboard: 'Көзөмөл панели',
        navDashboard: 'Көзөмөл панели',
        navInfo: 'ПД маалымат',
        navPatient: 'Пациенттин профили',
        navVoice: 'Сөз баалоо',
        navTremor: 'Трембалат баалоо',
        navGait: 'Жүрүш баалоо',
        navFacial: 'Жүз сөз-серте',
        navQuestions: 'Суроолор',
        navSpiral: 'Спираль сүрөтү',
        navResults: 'Натыйжалар',
        navReport: 'Отчет',
        navigationTitle: 'Навигация',
        disclaimerText: 'Зерттөө прототиби гана',
        
        dashboardTitle: 'Көзөмөл панели',
        dashboardDesc: 'Клиникалык баалоонун сереп-чыгаачысы',
        noPatientText: 'Пациенттик маалымат жок',
        voiceBoxTitle: 'Сөз',
        tremorBoxTitle: 'Трембалат',
        gaitBoxTitle: 'Жүрүш',
        facialBoxTitle: 'Жүз',
        questionsBoxTitle: 'Суроолор',
        spiralBoxTitle: 'Спираль',
        voiceStatus: 'Башталган жок',
        tremorStatus: 'Башталган жок',
        gaitStatus: 'Башталган жок',
        facialStatus: 'Башталган жок',
        questionsStatus: 'Башталган жок',
        spiralStatus: 'Башталган жок',
        startBtn: 'Баалоону башта',
        
        patientTitle: 'Пациенттин профили',
        patientDesc: 'Толук демографиялык маалымат',
        labelFirstName: 'Биринчи аты',
        labelLastName: 'Фамилия',
        labelDOB: 'Туулган датасы',
        labelGender: 'Жынысы',
        labelCountry: 'Өлкө',
        labelPhone: 'Телефон',
        labelEmail: 'Электрондук почта',
        labelMedicalId: 'Медициналык каттоосунун ID',
        optMale: 'Эркек',
        optFemale: 'Аял',
        optOther: 'Башка',
        savePatientBtn: 'Профилди сохра',
        patientSaved: 'Пациенттин профили сиктүүчүлүк менен сохранена!',
        
        infoTitle: 'Паркинсон ооруусунун маалыматы',
        infoSubtitle: 'Клиникалык фонду жана MDS-UPDRS 3-бөлүк',
        whatIsPDTitle: 'Паркинсон ооруусу деген эмне?',
        whatIsPDText: 'Трембалат, брадикинезия, катуулугу жана постураль нестабилдүүлүк менен сипатталган өнүгүүчү нейродегенеративдүү ооруу.',
        updrsTitle: 'MDS-UPDRS бөлүк 3 баалоо',
        scoreHeader: 'Баал',
        severityHeader: 'Оорулуулук',
        sev0: 'Нормалдуу',
        sev1: 'Жеңил',
        sev2: 'Орто',
        sev3: 'Орточо',
        sev4: 'Катуу',
        
        voiceTitle: 'Сөз баалоо',
        voiceDesc: '3 сынамалануу жээ 6 секунд',
        voiceInstructions: 'Сиз 3 сынамалануу жазалач. Баштоо үчүн төмөндө чыкса.',
        startVoiceBtn: '🎤 Жазууну баш',
        countdownText: 'Башталууда...',
        recordingText: 'Жазууда...',
        trialResultsTitle: 'Сынамалануунун натыйжалары',
        jitterLabel: 'Jitter (%)',
        shimmerLabel: 'Shimmer (дБ)',
        hnrLabel: 'HNR (дБ)',
        f0Label: 'F0 (Гц)',
        voiceNextBtn: '🎤 Кийинки сынамалануу',
        voiceCompleteBtn: '✓ Сынамалануу толугу',
        
        tremorTitle: 'Трембалат баалоо',
        tremorDesc: 'Куралды 10 секунд бир эле жерде кармагыла',
        tremorInstructions: 'Кайсы колдун сынамалануусун тандагыла:',
        leftHandBtn: '👈 Сол кол',
        rightHandBtn: '👉 Оң кол',
        tremorCountText: 'Башталууда...',
        tremorRecText: 'Жазууда...',
        tremorMetricsTitle: 'Трембалат метрикалары',
        frequencyLabel: 'Жыштык (Гц)',
        amplitudeLabel: 'Амплитуда (м/с²)',
        powerLabel: 'Чүч (дБ)',
        tremorCompleteBtn: '✓ Сынамалануу толугу',
        
        gaitTitle: 'Жүрүш баалоо',
        gaitDesc: 'Камера-негиздүү жүрүш талдоосу (15 сек)',
        gaitInstructions: 'Өзүңүзүн кадрга коюп, баштоо үчүн чыкса.',
        startGaitBtn: '📹 Камераны баш',
        gaitRecText: 'Талдоонун аракети...',
        cadenceLabel: 'Ритм (кадам/мин)',
        strideLabel: 'Кадам узундугу (м)',
        speedLabel: 'Ылдамдыгы (м/с)',
        gaitCompleteBtn: '✓ Сынамалануу толугу',
        greenSkeleton: 'ЖЕҢ СКЕЛЕТ КӨРҮНҮП ЖАТАТ',
        
        facialTitle: 'Жүз сөз-серте баалоо',
        facialDesc: 'Камера-негиздүү жүз талдоосу (10 сек)',
        facialInstructions: 'Жүзүңүзүн кадрга коюп, баштоо үчүн чыкса.',
        startFacialBtn: '📹 Камераны баш',
        facialRecText: 'Талдоонун аракети...',
        blinkLabel: 'Көзүмдүн ырамалануу сыплыгы (/мин)',
        jawLabel: 'Челюстьна ачылышы (см)',
        mouthLabel: 'Аган туура энесинин туурасы (см)',
        facialCompleteBtn: '✓ Сынамалануу толугу',
        magentaMesh: 'MAGENТА ЖҮЗ ТҮРҮ КӨРҮНҮП ЖАТАТ',
        
        questionsTitle: 'Суроолор баалоо',
        q1Label: '1. Жүрүштүн жайлуулугун (брадикинезияны) сезешби?',
        q2Label: '2. Колдорду же буттарыңызда катуулук чектүүлүк бармы?',
        q3Label: '3. Балансты сактоо көйгөйлүк же түшүүнүн коркусу бармы?',
        q1No: 'Жок',
        q1Sometimes: 'Кээде',
        q1Often: 'Көп',
        q1Always: 'Дайма',
        q2No: 'Жок',
        q2Sometimes: 'Кээде',
        q2Often: 'Көп',
        q2Always: 'Дайма',
        q3No: 'Жок',
        q3Sometimes: 'Кээде',
        q3Often: 'Көп',
        q3Always: 'Дайма',
        submitQuestionsBtn: 'Жооптонорду сохра',
        
        spiralTitle: 'Спираль сүрөтүнүн сынамалануусу',
        spiralDesc: 'Саймалуу сөөсүн чала менен же стилусу менен тартса',
        refSpiralTitle: 'Салыштыруу',
        yourSpiralTitle: 'Сизин сүрөтүңүз',
        clearBtn: 'Тазалоо',
        tremorIndexLabel: 'Трембалат индекси',
        pathLengthLabel: 'Жолдун узундугу (px)',
        velocityLabel: 'Ылдамдыгы (px/сек)',
        calcSpiralBtn: 'Метрикаларды эсепте',
        spiralCompleteBtn: '✓ Сынамалануу толугу',
        
        resultsTitle: 'Баалоонун натыйжалары',
        resultsDesc: 'Толук MDS-UPDRS төлөрөлөсү',
        domainHeader: 'Чөлкөм',
        scoreHeader2: 'Баал (0-4)',
        severityHeader2: 'Оорулуулук',
        generateReportBtn: '📄 Отчетту түз',
        
        reportTitle: 'Клиникалык отчет',
        patientInfoTitle: 'Пациенттик маалымат',
        assessmentSummaryTitle: 'Баалоонун төлөрөлөсү',
        rptNameLabel: 'Аты:',
        rptAgeLabel: 'Жашы:',
        rptGenderLabel: 'Жынысы:',
        rptCountryLabel: 'Өлкө:',
        rptEmailLabel: 'Электрондук почта:',
        rptVoiceSevLabel: 'Сөз оорулуулугу:',
        rptTremorSevLabel: 'Трембалат оорулуулугу:',
        rptGaitSevLabel: 'Жүрүш оорулуулугу:',
        rptFacialSevLabel: 'Жүз оорулуулугу:',
        rptCogSevLabel: 'Ойлоо оорулуулугу:',
        rptCoordSevLabel: 'Координация оорулуулугу:',
        disclaimerNote: 'Клиникалык чеке: Бул зерттөө экранын куралы. Ар дайма диагностика жана дарылоо чечимдери үчүн квалификалык дарыгер менен кеме.',
        downloadPDFBtn: '📥 PDF отчетту жүктөө',
        
        countries: {
            IN: 'Индия',
            US: 'Америка Кошмо Штаттары',
            UK: 'Өлкөнүн Англия',
            CA: 'Канада',
            AU: 'Австралия',
            DE: 'Германия',
            FR: 'Франция',
            JP: 'Япония',
            CN: 'Чыгат',
            BR: 'Бразилия',
            RU: 'Россия',
            KG: 'Кыргызстан',
            KZ: 'Казахстан',
        }
    },

    kz: { // KAZAKH (Қазақша)
        appTitle: 'НейроКомпас-ПД',
        version: 'v6.0',
        subtitle: 'Клиникалық бағалау платформасы',
        
        dashboard: 'Басқару панелі',
        navDashboard: 'Басқару панелі',
        navInfo: 'ПД ақпараты',
        navPatient: 'Пациенттің профилі',
        navVoice: 'Сөйлеу бағалауы',
        navTremor: 'Дрожаңды бағалауы',
        navGait: 'Жүргіліс бағалауы',
        navFacial: 'Бет өрнегі',
        navQuestions: 'Сұрақтар',
        navSpiral: 'Спираль сызба',
        navResults: 'Нәтижелер',
        navReport: 'Есеп',
        navigationTitle: 'Навигация',
        disclaimerText: 'Тек зерттеу прототипі',
        
        dashboardTitle: 'Басқару панелі',
        dashboardDesc: 'Клиникалық бағалаудың шолуы',
        noPatientText: 'Пациенттің ақпараты жоқ',
        voiceBoxTitle: 'Сөйлеу',
        tremorBoxTitle: 'Дрожаң',
        gaitBoxTitle: 'Жүргіліс',
        facialBoxTitle: 'Бет',
        questionsBoxTitle: 'Сұрақтар',
        spiralBoxTitle: 'Спираль',
        voiceStatus: 'Басталмады',
        tremorStatus: 'Басталмады',
        gaitStatus: 'Басталмады',
        facialStatus: 'Басталмады',
        questionsStatus: 'Басталмады',
        spiralStatus: 'Басталмады',
        startBtn: 'Бағалауды бастау',
        
        patientTitle: 'Пациенттің профилі',
        patientDesc: 'Толық демографиялық ақпарат',
        labelFirstName: 'Аты',
        labelLastName: 'Тегі',
        labelDOB: 'Туған күні',
        labelGender: 'Жынысы',
        labelCountry: 'Ел',
        labelPhone: 'Телефон',
        labelEmail: 'Электрондық пошта',
        labelMedicalId: 'Медициналық карта нөмірі',
        optMale: 'Ер',
        optFemale: 'Әйел',
        optOther: 'Басқа',
        savePatientBtn: 'Профильді сақта',
        patientSaved: 'Пациенттің профилі сәтті сақталды!',
        
        infoTitle: 'Паркинсон ауруының ақпараты',
        infoSubtitle: 'Клиникалық негіз және MDS-UPDRS 3-бөлім',
        whatIsPDTitle: 'Паркинсон ауруы дегеніміз не?',
        whatIsPDText: 'Дрожаң, брадикинезия, қатаю және сағыштық ішінара анықталатын ілеспелі нейродегенеративті ауру.',
        updrsTitle: 'MDS-UPDRS 3-бөлім бағалауы',
        scoreHeader: 'Ұпай',
        severityHeader: 'Ауырлығы',
        sev0: 'Норма',
        sev1: 'Аз',
        sev2: 'Орта',
        sev3: 'Орташа',
        sev4: 'Ауыр',
        
        voiceTitle: 'Сөйлеу бағалауы',
        voiceDesc: '3 сынамаланып 6 секундтан',
        voiceInstructions: 'Сіз 3 сынамаланысты жазалайсыз. Бастау үшін төмеңде шертіңіз.',
        startVoiceBtn: '🎤 Жазып бастау',
        countdownText: 'Басталуда...',
        recordingText: 'Жазуда...',
        trialResultsTitle: 'Сынамалану нәтижелері',
        jitterLabel: 'Jitter (%)',
        shimmerLabel: 'Shimmer (дБ)',
        hnrLabel: 'HNR (дБ)',
        f0Label: 'F0 (Гц)',
        voiceNextBtn: '🎤 Келесі сынамалану',
        voiceCompleteBtn: '✓ Сынамалануды аяқта',
        
        tremorTitle: 'Дрожаңды бағалауы',
        tremorDesc: 'Құралды 10 секунд бір жерде ұстаңыз',
        tremorInstructions: 'Қайсы қолдың сынамаланысын таңдаңыз:',
        leftHandBtn: '👈 Сол қол',
        rightHandBtn: '👉 Оң қол',
        tremorCountText: 'Басталуда...',
        tremorRecText: 'Жазуда...',
        tremorMetricsTitle: 'Дрожаңдың метрикалары',
        frequencyLabel: 'Жиілігі (Гц)',
        amplitudeLabel: 'Амплитудасы (м/с²)',
        powerLabel: 'Күші (дБ)',
        tremorCompleteBtn: '✓ Сынамалануды аяқта',
        
        gaitTitle: 'Жүргіліс бағалауы',
        gaitDesc: 'Камера негіздегі жүргіліс анализі (15 сек)',
        gaitInstructions: 'Өзіңізді кадрға салып, бастау үшін шертіңіз.',
        startGaitBtn: '📹 Камераны іске қосу',
        gaitRecText: 'Анализ аралуда...',
        cadenceLabel: 'Қадамдық (қадам/мин)',
        strideLabel: 'Қадам ұзындығы (м)',
        speedLabel: 'Қарықты (м/с)',
        gaitCompleteBtn: '✓ Сынамалануды аяқта',
        greenSkeleton: 'ЖАСЫЛ СКЕЛЕТ КӨРІНЕДІ',
        
        facialTitle: 'Бет өрнегінің бағалауы',
        facialDesc: 'Камера негіздегі бет анализі (10 сек)',
        facialInstructions: 'Бетіңізді кадрға салып, бастау үшін шертіңіз.',
        startFacialBtn: '📹 Камераны іске қосу',
        facialRecText: 'Анализ аралуда...',
        blinkLabel: 'Көзді жығылжыту сыңы (/мин)',
        jawLabel: 'Жақты ашылуы (см)',
        mouthLabel: 'Ауыз ені (см)',
        facialCompleteBtn: '✓ Сынамалануды аяқта',
        magentaMesh: 'ОРАСЫЛ БОР БЕТ ТОРЫ КӨРІНЕДІ',
        
        questionsTitle: 'Сұрақтар бағалауы',
        q1Label: '1. Қозғалыстың баяулығын (брадикинезияны) сезесіз бе?',
        q2Label: '2. Қолдарыңызда немесе аяқтарыңызда қатаю/құрпылау бар ма?',
        q3Label: '3. Балансты сақтау мәселелері немесе құлау қаупі бар ма?',
        q1No: 'Жоқ',
        q1Sometimes: 'Кейде',
        q1Often: 'Көбінесе',
        q1Always: 'Әрқашан',
        q2No: 'Жоқ',
        q2Sometimes: 'Кейде',
        q2Often: 'Көбінесе',
        q2Always: 'Әрқашан',
        q3No: 'Жоқ',
        q3Sometimes: 'Кейде',
        q3Often: 'Көбінесе',
        q3Always: 'Әрқашан',
        submitQuestionsBtn: 'Жауаптарды сақта',
        
        spiralTitle: 'Спираль сызба сынамалануы',
        spiralDesc: 'Ұстас/стильус пайдаланып тегіс спираль сыз',
        refSpiralTitle: 'Салыстыру',
        yourSpiralTitle: 'Сіздің сызбаңыз',
        clearBtn: 'Тазалау',
        tremorIndexLabel: 'Дрожаңды индексі',
        pathLengthLabel: 'Жолдың ұзындығы (px)',
        velocityLabel: 'Жылдамдығы (px/сек)',
        calcSpiralBtn: 'Метрикаларды есептеу',
        spiralCompleteBtn: '✓ Сынамалануды аяқта',
        
        resultsTitle: 'Бағалаудың нәтижелері',
        resultsDesc: 'Толық MDS-UPDRS қорытындысы',
        domainHeader: 'Облысы',
        scoreHeader2: 'Ұпай (0-4)',
        severityHeader2: 'Ауырлығы',
        generateReportBtn: '📄 Есепті құру',
        
        reportTitle: 'Клиникалық есеп',
        patientInfoTitle: 'Пациенттің ақпараты',
        assessmentSummaryTitle: 'Бағалаудың қорытындысы',
        rptNameLabel: 'Аты:',
        rptAgeLabel: 'Жасы:',
        rptGenderLabel: 'Жынысы:',
        rptCountryLabel: 'Ел:',
        rptEmailLabel: 'Электрондық пошта:',
        rptVoiceSevLabel: 'Сөйлеудің ауырлығы:',
        rptTremorSevLabel: 'Дрожаңдың ауырлығы:',
        rptGaitSevLabel: 'Жүргіліске ауырлығы:',
        rptFacialSevLabel: 'Бет ауырлығы:',
        rptCogSevLabel: 'Ойлау ауырлығы:',
        rptCoordSevLabel: 'Үйлестіру ауырлығы:',
        disclaimerNote: 'Клиникалық әмидтеме: Бұл зерттеу сүзгі құралы. Диагностика және емеу шешімдері үшін әрқашан біліктілік врачпен кеңес алыңыз.',
        downloadPDFBtn: '📥 PDF есептегі жүктеу',
        
        countries: {
            IN: 'Индия',
            US: 'Америка Құрама Штаттары',
            UK: 'Британдық Падишалық',
            CA: 'Канада',
            AU: 'Австралия',
            DE: 'Германия',
            FR: 'Франция',
            JP: 'Жапония',
            CN: 'Қытай',
            BR: 'Бразилия',
            RU: 'Ресей',
            KG: 'Қырғызстан',
            KZ: 'Қазақстан',
        }
    }
};

// ============================================
// TRANSLATION FUNCTION
// ============================================
function t(key) {
    const lang = LANGUAGES[currentLanguage] || LANGUAGES['en'];
    return lang[key] || key;
}

function updateLanguage() {
    const lang = LANGUAGES[currentLanguage] || LANGUAGES['en'];
    
    // Update all text elements by ID
    for (const [key, value] of Object.entries(lang)) {
        const element = document.getElementById(key);
        if (element && typeof value === 'string') {
            element.textContent = value;
        }
    }
    
    // Update country dropdown
    const countrySelect = document.getElementById('country');
    if (countrySelect) {
        const selectedValue = countrySelect.value;
        countrySelect.innerHTML = '<option value="">Select</option>';
        
        for (const [code, name] of Object.entries(lang.countries || {})) {
            const option = document.createElement('option');
            option.value = code;
            option.textContent = name;
            countrySelect.appendChild(option);
        }
        
        if (selectedValue) {
            countrySelect.value = selectedValue;
        }
    }
    
    localStorage.setItem('language', currentLanguage);
}

// Initialize on load
document.addEventListener('DOMContentLoaded', updateLanguage);
