// NeuroCompass-PD v2.1 - COMPLETE LANGUAGE SUPPORT
// FIXED: All keys match assessment.js calls, consistent naming

window.LANGUAGES = {
    en: {
        // Navigation
        navdashboard: 'Dashboard',
        navinfo: 'PD Information',
        navpatient: 'Patient Profile',
        navvoice: 'Speech Assessment',
        navtremor: 'Tremor Assessment',
        navgait: 'Gait Assessment',
        navfacial: 'Facial Expression',
        navquestions: 'Questions',
        navspiral: 'Spiral Drawing',
        navresults: 'Results',
        navreport: 'Report',
        
        // Common
        navigation: 'Navigation',
        language: 'Language',
        voiceassistant: 'Voice Assistant',
        dashboard: 'Dashboard',
        welcome: 'Welcome to NeuroCompass-PD',
        mdsUPDRS: 'MDS-UPDRS Clinical Assessment Suite',
        
        // Dashboard
        dashtitle: 'Clinical Assessment Dashboard',
        dashsubtitle: 'MDS-UPDRS Part III digital screening summary',
        dashpatienttitle: 'Patient Profile',
        dashpatientdesc: 'Complete demographic and contact details.',
        dashscreeningtitle: 'Screening Tests',
        dashscreeningdesc: 'Speech, tremor, gait and facial expression.',
        dashreporttitle: 'Radar Summary',
        dashreportdesc: 'Downloadable radar chart with domain scores.',
        dashstatusrequired: 'Required',
        dashstatuslocked: 'Locked',
        dashstart: 'Begin Assessment Journey',
        dashpatientsnap: 'No patient information available.',
        
        // Info section
        infotitle: 'Parkinson\'s Disease Information',
        infosubtitle: 'Clinical background and MDS-UPDRS Part III protocol',
        infopdtitle: 'What is Parkinson\'s?',
        infopdtext: 'Progressive neurodegenerative disorder with tremor, bradykinesia, rigidity and postural instability.',
        infoupdrstitle: 'MDS-UPDRS Part III',
        infoupdrstext: 'Motor examination with 18 items scored 0-4 (0 normal, 4 severe).',
        infobiomarkertitle: 'Digital Biomarkers',
        infobiomarkertext: 'Speech, tremor, gait and facial metrics captured as objective digital signatures.',
        infonote: 'This is a research prototype—interpret with clinician oversight.',
        infonext: 'Proceed to Patient Contact Information',
        
        // Patient form
        patienttitle: 'Patient Demographic & Contact Information',
        patientsubtitle: 'Required for documentation before screening',
        labelfirstname: 'First Name',
        labellastname: 'Last Name',
        labeldob: 'Date of Birth',
        labelgender: 'Gender',
        genderselect: 'Select Gender',
        gendermale: 'Male',
        genderfemale: 'Female',
        genderother: 'Other',
        genderna: 'Prefer not to say',
        labelcountry: 'Country Code',
        labelphone: 'Phone Number',
        hintphone: 'Enter digits only, without country code',
        labelemail: 'Email Address',
        labelmedicalid: 'Medical Record Number',
        patientnote: 'All required fields must be valid before screening tests unlock.',
        patientsave: 'Save & Unlock Screening',
        
        // Speech Assessment
        speechassessmenttitle: 'Speech Assessment',
        speechassessmentdesc: 'Record 3 trials of sustained "AAAAA" (5 seconds each)',
        voicetrialtext: 'Trial of 3',
        voicestarttext: 'Start Recording',
        voicestoptext: 'Stop Recording',
        voiceplaytext: 'Play Recording',
        voicenexttext: 'Next Trial',
        voicecompletetext: 'Complete Speech Assessment',
        
        // Tremor Assessment
        tremorassessmenttitle: 'Tremor Assessment',
        tremorassessmentdesc: 'Hold device steady for 10 seconds - DeviceMotion captures accelerometer data',
        tremorhandtext: 'Select Hand',
        tremorcountdowntext: 'Starting in',
        tremorretesttext: 'Test Other Hand',
        tremorcompletetext: 'Complete Tremor Assessment',
        
        // Gait Assessment
        gaitassessmenttitle: 'Gait Assessment',
        gaitassessmentdesc: 'Walk in place or forward - MediaPipe Pose tracks ankle landmarks for cadence and stride length',
        gaitstarttext: 'Start Gait Recording',
        gaitstoptext: 'Stop Recording',
        gaitfliptext: 'Flip Camera',
        gaitcompletetext: 'Complete Gait Assessment',
        
        // Facial Assessment
        facialassessmenttitle: 'Facial Expression Assessment',
        facialassessmentdesc: 'Look at camera - MediaPipe Face Mesh tracks blink rate and jaw opening',
        facialstarttext: 'Start Facial Recording',
        facialstoptext: 'Stop Recording',
        facialfliptext: 'Flip Camera',
        facialcompletetext: 'Complete Facial Assessment',
        
        // Questions
        questionsassessmenttitle: 'Questions Assessment',
        questionsassessmentdesc: 'Answer a short set of clinical questions to support screening context',
        q1: '1. Do you experience slowness of movement (bradykinesia)?',
        q2: '2. Do you have stiffness/rigidity in arms or legs?',
        q3: '3. Do you have balance issues or near falls?',
        optno: 'No',
        optsometimes: 'Sometimes',
        optoften: 'Often',
        questionsnote: 'Note: This is a supportive questionnaire and not a diagnosis.',
        questionssave: 'Save Questions',
        
        // Spiral
        spiraledrawingtitle: 'Spiral Drawing Test',
        spiraledrawingdesc: 'Draw a spiral smoothly using your finger/stylus',
        spiralreftext: 'Reference Spiral',
        spiralyourtext: 'Your Drawing',
        spiralstarttext: 'Start Drawing',
        spiralcleartext: 'Clear Drawing',
        spiralsavetext: 'Save Spiral',
        spiralnote: 'Spiral drawing is a common motor task used to observe tremor and control.',
        
        // Results
        resultstitle: 'Assessment Results',
        reporttitle: 'Clinical Assessment Report',
        reportpationtitle: 'Patient Information',
        reportsummarytitle: 'Assessment Summary',
        reportdetailedtitle: 'Detailed Results',
        downloadpdf: 'Download PDF Report',
        
        // Metrics
        jitter: 'Jitter (%)',
        shimmer: 'Shimmer (dB)',
        hnr: 'HNR (dB)',
        f0: 'Pitch (Hz)',
        frequency: 'Frequency (Hz)',
        amplitude: 'Amplitude (m/s²)',
        power: 'Power (dB)',
        cadence: 'Cadence (steps/min)',
        strideLength: 'Stride Length (m)',
        speed: 'Speed (m/s)',
        blinkRate: 'Blink Rate (/min)',
        jawOpening: 'Jaw Opening (cm)',
        mouthWidth: 'Mouth Width (cm)',
        tremorIndex: 'Tremor Index',
        pathLength: 'Path Length (px)',
        velocity: 'Velocity (px/step)',
        updrsScore: 'UPDRS Score',
        
        // Messages
        fillCorrect: 'Please fill the information correctly.',
        saved: 'Patient information saved. Screening tests unlocked.',
        voiceOn: 'Voice On',
        voiceOff: 'Voice Off',
        reference: 'Reference',
        yourDrawing: 'Your Drawing',
        startingIn: 'Starting in'
    },
    
    hi: {
        // Navigation
        navdashboard: 'डैशबोर्ड',
        navinfo: 'पीडी जानकारी',
        navpatient: 'रोगी प्रोफाइल',
        navvoice: 'वाणी मूल्यांकन',
        navtremor: 'कंपन मूल्यांकन',
        navgait: 'गति मूल्यांकन',
        navfacial: 'चेहरे की अभिव्यक्ति',
        navquestions: 'प्रश्न',
        navspiral: 'सर्पिल चित्र',
        navresults: 'परिणाम',
        navreport: 'रिपोर्ट',
        
        // Common
        navigation: 'नेविगेशन',
        language: 'भाषा',
        voiceassistant: 'आवाज सहायक',
        dashboard: 'डैशबोर्ड',
        welcome: 'NeuroCompass-PD में आपका स्वागत है',
        mdsUPDRS: 'एमडीएस-यूपीडीआरएस नैदानिक मूल्यांकन सूट',
        
        // Dashboard
        dashtitle: 'नैदानिक मूल्यांकन डैशबोर्ड',
        dashsubtitle: 'एमडीएस-यूपीडीआरएस भाग III डिजिटल स्क्रीनिंग सारांश',
        dashpatienttitle: 'रोगी प्रोफाइल',
        dashpatientdesc: 'जनसांख्यिकीय और संपर्क विवरण पूर्ण करें।',
        dashscreeningtitle: 'स्क्रीनिंग परीक्षण',
        dashscreeningdesc: 'वाणी, कंपन, गति और चेहरे की अभिव्यक्ति।',
        dashreporttitle: 'राडार सारांश',
        dashreportdesc: 'डोमेन स्कोर के साथ डाउनलोड योग्य राडार चार्ट।',
        dashstatusrequired: 'आवश्यक',
        dashstatuslocked: 'बंद',
        dashstart: 'मूल्यांकन यात्रा शुरू करें',
        dashpatientsnap: 'कोई रोगी जानकारी उपलब्ध नहीं है।',
        
        // Info section
        infotitle: 'पार्किंसन रोग की जानकारी',
        infosubtitle: 'नैदानिक पृष्ठभूमि और एमडीएस-यूपीडीआरएस भाग III प्रोटोकॉल',
        infopdtitle: 'पार्किंसन क्या है?',
        infopdtext: 'कंपन, ब्रैडीकिनेसिया, कठोरता और मुद्रा अस्थिरता की विशेषता वाली प्रगतिशील न्यूरोडीजेनेरेटिव विकार।',
        infoupdrstitle: 'एमडीएस-यूपीडीआरएस भाग III',
        infoupdrstext: '18 आइटम के साथ मोटर परीक्षा 0-4 स्कोर किए गए (0 सामान्य, 4 गंभीर)।',
        infobiomarkertitle: 'डिजिटल बायोमार्कर',
        infobiomarkertext: 'वाणी, कंपन, गति और चेहरे की मेट्रिक्स को उद्देश्यपूर्ण डिजिटल हस्ताक्षर के रूप में कैप्चर किया गया।',
        infonote: 'यह एक अनुसंधान प्रोटोटाइप है। नैदानिक निरीक्षण के साथ व्याख्या करें।',
        infonext: 'रोगी संपर्क जानकारी के लिए आगे बढ़ें',
        
        // Patient form
        patienttitle: 'रोगी जनसांख्यिकी और संपर्क जानकारी',
        patientsubtitle: 'स्क्रीनिंग से पहले प्रलेखन के लिए आवश्यक',
        labelfirstname: 'पहला नाम',
        labellastname: 'अंतिम नाम',
        labeldob: 'जन्म की तारीख',
        labelgender: 'लिंग',
        genderselect: 'लिंग चुनें',
        gendermale: 'पुरुष',
        genderfemale: 'महिला',
        genderother: 'अन्य',
        genderna: 'नहीं कहना पसंद करते',
        labelcountry: 'देश कोड',
        labelphone: 'फोन नंबर',
        hintphone: 'केवल अंक दर्ज करें, देश कोड के बिना',
        labelemail: 'ईमेल पता',
        labelmedicalid: 'चिकित्सा रिकॉर्ड संख्या',
        patientnote: 'स्क्रीनिंग परीक्षण अनलॉक करने से पहले सभी आवश्यक फील्ड मान्य होने चाहिए।',
        patientsave: 'सहेजें और स्क्रीनिंग अनलॉक करें',
        
        // Speech Assessment
        speechassessmenttitle: 'वाणी मूल्यांकन',
        speechassessmentdesc: '"AAAAA" के 3 परीक्षणों को रिकॉर्ड करें (प्रत्येक 5 सेकंड)',
        voicetrialtext: 'का परीक्षण',
        voicestarttext: 'रिकॉर्डिंग शुरू करें',
        voicestoptext: 'रिकॉर्डिंग बंद करें',
        voiceplaytext: 'रिकॉर्डिंग चलाएं',
        voicenexttext: 'अगला परीक्षण',
        voicecompletetext: 'वाणी मूल्यांकन पूर्ण करें',
        
        // Tremor Assessment
        tremorassessmenttitle: 'कंपन मूल्यांकन',
        tremorassessmentdesc: 'डिवाइस को 10 सेकंड के लिए स्थिर रखें - DeviceMotion त्वरणमापी डेटा कैप्चर करता है',
        tremorhandtext: 'हाथ चुनें',
        tremorcountdowntext: 'शुरुआत हो रही है',
        tremorretesttext: 'दूसरा हाथ परीक्षण करें',
        tremorcompletetext: 'कंपन मूल्यांकन पूर्ण करें',
        
        // Gait Assessment
        gaitassessmenttitle: 'गति मूल्यांकन',
        gaitassessmentdesc: 'चलें या आगे बढ़ें - MediaPipe Pose टखने के स्थलों को ट्रैक करता है',
        gaitstarttext: 'गति रिकॉर्डिंग शुरू करें',
        gaitstoptext: 'रिकॉर्डिंग बंद करें',
        gaitfliptext: 'कैमरा पलटें',
        gaitcompletetext: 'गति मूल्यांकन पूर्ण करें',
        
        // Facial Assessment
        facialassessmenttitle: 'चेहरे की अभिव्यक्ति मूल्यांकन',
        facialassessmentdesc: 'कैमरे को देखें - MediaPipe Face Mesh पलक दर को ट्रैक करता है',
        facialstarttext: 'चेहरा रिकॉर्डिंग शुरू करें',
        facialstoptext: 'रिकॉर्डिंग बंद करें',
        facialfliptext: 'कैमरा पलटें',
        facialcompletetext: 'चेहरे की अभिव्यक्ति मूल्यांकन पूर्ण करें',
        
        // Questions
        questionsassessmenttitle: 'प्रश्न मूल्यांकन',
        questionsassessmentdesc: 'नैदानिक प्रश्नों का उत्तर दें',
        q1: '1. क्या आप आंदोलन की धीमापन (ब्रैडीकिनेसिया) का अनुभव करते हैं?',
        q2: '2. क्या आपके पास बाहों या पैरों में कठोरता है?',
        q3: '3. क्या आपको संतुलन समस्याएं या गिरने का खतरा है?',
        optno: 'नहीं',
        optsometimes: 'कभी-कभी',
        optoften: 'अक्सर',
        questionsnote: 'नोट: यह एक सहायक प्रश्नावली है।',
        questionssave: 'प्रश्न सहेजें',
        
        // Spiral
        spiraledrawingtitle: 'सर्पिल चित्र परीक्षण',
        spiraledrawingdesc: 'एक सर्पिल को सुचारु रूप से ड्रॉ करें',
        spiralreftext: 'संदर्भ सर्पिल',
        spiralyourtext: 'आपकी ड्राइंग',
        spiralstarttext: 'ड्राइंग शुरू करें',
        spiralcleartext: 'स्पष्ट करें',
        spiralsavetext: 'सर्पिल सहेजें',
        spiralnote: 'सर्पिल चित्र एक सामान्य मोटर कार्य है।',
        
        // Results
        resultstitle: 'परिणाम',
        reporttitle: 'नैदानिक मूल्यांकन रिपोर्ट',
        reportpationtitle: 'रोगी जानकारी',
        reportsummarytitle: 'मूल्यांकन सारांश',
        reportdetailedtitle: 'विस्तृत परिणाम',
        downloadpdf: 'पीडीएफ रिपोर्ट डाउनलोड करें',
        
        // Metrics
        jitter: 'जिटर (%)',
        shimmer: 'शिमर (डीबी)',
        hnr: 'एचएनआर (डीबी)',
        f0: 'पिच (हर्ट्ज)',
        frequency: 'आवृत्ति (हर्ट्ज)',
        amplitude: 'आयाम (मी/एस²)',
        power: 'शक्ति (डीबी)',
        cadence: 'लय (कदम/मिनट)',
        strideLength: 'स्ट्राइड लंबाई (मी)',
        speed: 'गति (मी/एस)',
        blinkRate: 'पलक दर (/मिनट)',
        jawOpening: 'जबड़े की खुलावट (सेमी)',
        mouthWidth: 'मुँह की चौड़ाई (सेमी)',
        tremorIndex: 'कंपन सूचकांक',
        pathLength: 'पथ की लंबाई (पीएक्स)',
        velocity: 'वेग (पीएक्स/कदम)',
        updrsScore: 'यूपीडीआरएस स्कोर',
        
        // Messages
        fillCorrect: 'कृपया जानकारी सही ढंग से भरें।',
        saved: 'रोगी की जानकारी सहेजी गई।',
        voiceOn: 'आवाज चालू',
        voiceOff: 'आवाज बंद',
        reference: 'संदर्भ',
        yourDrawing: 'आपकी ड्राइंग',
        startingIn: 'शुरुआत'
    },
    
    ru: {
        // Navigation
        navdashboard: 'Панель управления',
        navinfo: 'Информация о БП',
        navpatient: 'Профиль пациента',
        navvoice: 'Оценка речи',
        navtremor: 'Оценка тремора',
        navgait: 'Оценка походки',
        navfacial: 'Мимические выражения',
        navquestions: 'Вопросы',
        navspiral: 'Рисование спирали',
        navresults: 'Результаты',
        navreport: 'Отчет',
        
        // Common
        navigation: 'Навигация',
        language: 'Язык',
        voiceassistant: 'Голосовой помощник',
        dashboard: 'Панель управления',
        welcome: 'Добро пожаловать в NeuroCompass-PD',
        mdsUPDRS: 'Клиническая шкала оценки БП (MDS-UPDRS)',
        
        // Dashboard
        dashtitle: 'Клиническая панель оценки',
        dashsubtitle: 'Цифровой скрининг MDS-UPDRS Часть III',
        dashpatienttitle: 'Профиль пациента',
        dashpatientdesc: 'Завершить демографические и контактные данные.',
        dashscreeningtitle: 'Тесты скрининга',
        dashscreeningdesc: 'Речь, тремор, походка и мимика.',
        dashreporttitle: 'Сводка радара',
        dashreportdesc: 'Загружаемая диаграмма радара с баллами по доменам.',
        dashstatusrequired: 'Требуется',
        dashstatuslocked: 'Заблокировано',
        dashstart: 'Начать оценку',
        dashpatientsnap: 'Информация о пациенте недоступна.',
        
        // Info section
        infotitle: 'Информация о болезни Паркинсона',
        infosubtitle: 'Клиническая справка и протокол MDS-UPDRS Часть III',
        infopdtitle: 'Что такое болезнь Паркинсона?',
        infopdtext: 'Прогрессирующее нейродегенеративное заболевание, характеризующееся тремором.',
        infoupdrstitle: 'MDS-UPDRS Часть III',
        infoupdrstext: 'Моторное обследование с 18 пунктами, оцениваемыми 0-4.',
        infobiomarkertitle: 'Цифровые биомаркеры',
        infobiomarkertext: 'Показатели речи, тремора, походки и лица.',
        infonote: 'Это исследовательский прототип. Интерпретируйте под клиническим контролем.',
        infonext: 'Перейти к контактной информации пациента',
        
        // Patient form
        patienttitle: 'Демографические и контактные данные пациента',
        patientsubtitle: 'Требуется для документирования перед скринингом',
        labelfirstname: 'Имя',
        labellastname: 'Фамилия',
        labeldob: 'Дата рождения',
        labelgender: 'Пол',
        genderselect: 'Выберите пол',
        gendermale: 'Мужской',
        genderfemale: 'Женский',
        genderother: 'Другое',
        genderna: 'Предпочитаю не говорить',
        labelcountry: 'Код страны',
        labelphone: 'Номер телефона',
        hintphone: 'Введите только цифры без кода страны',
        labelemail: 'Адрес электронной почты',
        labelmedicalid: 'Номер медицинской записи',
        patientnote: 'Все обязательные поля должны быть действительны перед разблокировкой тестов.',
        patientsave: 'Сохранить и разблокировать скрининг',
        
        // Speech Assessment
        speechassessmenttitle: 'Оценка речи',
        speechassessmentdesc: 'Запишите 3 пробы "AAAAA" (по 5 секунд каждая)',
        voicetrialtext: 'проба из 3',
        voicestarttext: 'Начать запись',
        voicestoptext: 'Остановить запись',
        voiceplaytext: 'Воспроизвести запись',
        voicenexttext: 'Следующая проба',
        voicecompletetext: 'Завершить оценку речи',
        
        // Tremor Assessment
        tremorassessmenttitle: 'Оценка тремора',
        tremorassessmentdesc: 'Удерживайте устройство неподвижно 10 секунд',
        tremorhandtext: 'Выберите руку',
        tremorcountdowntext: 'Начинается через',
        tremorretesttext: 'Тестировать другую руку',
        tremorcompletetext: 'Завершить оценку тремора',
        
        // Gait Assessment
        gaitassessmenttitle: 'Оценка походки',
        gaitassessmentdesc: 'Ходите на месте или вперед',
        gaitstarttext: 'Начать запись походки',
        gaitstoptext: 'Остановить запись',
        gaitfliptext: 'Перевернуть камеру',
        gaitcompletetext: 'Завершить оценку походки',
        
        // Facial Assessment
        facialassessmenttitle: 'Оценка мимики',
        facialassessmentdesc: 'Смотрите в камеру',
        facialstarttext: 'Начать запись лица',
        facialstoptext: 'Остановить запись',
        facialfliptext: 'Перевернуть камеру',
        facialcompletetext: 'Завершить оценку мимики',
        
        // Questions
        questionsassessmenttitle: 'Оценка по вопросам',
        questionsassessmentdesc: 'Ответьте на клинические вопросы',
        q1: '1. Испытываете ли вы замедленность движений?',
        q2: '2. У вас есть скованность в руках или ногах?',
        q3: '3. У вас есть проблемы с равновесием?',
        optno: 'Нет',
        optsometimes: 'Иногда',
        optoften: 'Часто',
        questionsnote: 'Примечание: Это вспомогательный опросник.',
        questionssave: 'Сохранить вопросы',
        
        // Spiral
        spiraledrawingtitle: 'Тест спирали',
        spiraledrawingdesc: 'Нарисуйте спираль плавно',
        spiralreftext: 'Эталонная спираль',
        spiralyourtext: 'Ваш рисунок',
        spiralstarttext: 'Начать рисование',
        spiralcleartext: 'Очистить',
        spiralsavetext: 'Сохранить спираль',
        spiralnote: 'Рисование спирали - это обычное моторное задание.',
        
        // Results
        resultstitle: 'Результаты',
        reporttitle: 'Клинический отчет об оценке',
        reportpationtitle: 'Информация о пациенте',
        reportsummarytitle: 'Сводка оценки',
        reportdetailedtitle: 'Подробные результаты',
        downloadpdf: 'Загрузить отчет PDF',
        
        // Metrics
        jitter: 'Джиттер (%)',
        shimmer: 'Шиммер (дБ)',
        hnr: 'ХНР (дБ)',
        f0: 'Высота (Гц)',
        frequency: 'Частота (Гц)',
        amplitude: 'Амплитуда (м/с²)',
        power: 'Мощность (дБ)',
        cadence: 'Темп (шагов/мин)',
        strideLength: 'Длина шага (м)',
        speed: 'Скорость (м/с)',
        blinkRate: 'Частота моргания (/мин)',
        jawOpening: 'Раскрытие челюсти (см)',
        mouthWidth: 'Ширина рта (см)',
        tremorIndex: 'Индекс тремора',
        pathLength: 'Длина пути (px)',
        velocity: 'Скорость (px/шаг)',
        updrsScore: 'Оценка UPDRS',
        
        // Messages
        fillCorrect: 'Пожалуйста, заполните информацию правильно.',
        saved: 'Информация о пациенте сохранена.',
        voiceOn: 'Голос включен',
        voiceOff: 'Голос отключен',
        reference: 'Эталон',
        yourDrawing: 'Ваш рисунок',
        startingIn: 'Начинается через'
    }
};
