const LANGUAGES = {
    en: {
        welcome: 'Welcome to NeuroCompass-PD',
        dashboard: 'Dashboard',
        patientProfile: 'Patient Profile',
        tests: 'Tests',
        report: 'Report',
        startTests: 'Start Tests',
        complete: 'Complete',
        results: 'Results',
        required: 'Required',
        speech: 'Speech Assessment',
        tremor: 'Tremor Assessment',
        gait: 'Gait Assessment',
        facial: 'Facial Expression',
        questions: 'Questions',
        spiral: 'Spiral Drawing',
        fillPatient: 'Fill Patient Information',
        patientInfo: 'Patient Information',
        firstName: 'First Name',
        lastName: 'Last Name',
        dob: 'Date of Birth',
        gender: 'Gender',
        country: 'Country Code',
        phone: 'Phone',
        email: 'Email',
        medicalId: 'Medical ID',
        save: 'Save & Unlock Tests'
    },
    hi: {
        welcome: 'NeuroCompass-PD में आपका स्वागत है',
        dashboard: 'डैशबोर्ड',
        patientProfile: 'रोगी प्रोफाइल',
        tests: 'परीक्षण',
        report: 'रिपोर्ट',
        startTests: 'परीक्षण शुरू करें',
        complete: 'पूर्ण',
        results: 'परिणाम',
        required: 'आवश्यक',
        speech: 'वाणी मूल्यांकन',
        tremor: 'कंपन मूल्यांकन',
        gait: 'गति मूल्यांकन',
        facial: 'चेहरे की अभिव्यक्ति',
        questions: 'प्रश्न',
        spiral: 'सर्पिल चित्र',
        fillPatient: 'रोगी की जानकारी भरें',
        patientInfo: 'रोगी की जानकारी',
        firstName: 'पहला नाम',
        lastName: 'अंतिम नाम',
        dob: 'जन्म की तारीख',
        gender: 'लिंग',
        country: 'देश कोड',
        phone: 'फोन',
        email: 'ईमेल',
        medicalId: 'चिकित्सा आईडी',
        save: 'सहेजें और परीक्षण अनलॉक करें'
    },
    ru: {
        welcome: 'Добро пожаловать в NeuroCompass-PD',
        dashboard: 'Панель управления',
        patientProfile: 'Профиль пациента',
        tests: 'Тесты',
        report: 'Отчет',
        startTests: 'Начать тесты',
        complete: 'Завершить',
        results: 'Результаты',
        required: 'Требуется',
        speech: 'Оценка речи',
        tremor: 'Оценка тремора',
        gait: 'Оценка походки',
        facial: 'Мимические выражения',
        questions: 'Вопросы',
        spiral: 'Рисование спирали',
        fillPatient: 'Заполните информацию пациента',
        patientInfo: 'Информация о пациенте',
        firstName: 'Имя',
        lastName: 'Фамилия',
        dob: 'Дата рождения',
        gender: 'Пол',
        country: 'Код страны',
        phone: 'Телефон',
        email: 'Электронная почта',
        medicalId: 'Медицинский идентификатор',
        save: 'Сохранить и разблокировать тесты'
    }
};