// NeuroCompass-PD v6.0 - Multilingual Support System
// Supports: English, Hindi, Russian, Kyrgyz, Kazakh

let currentLanguage = 'en';

const LANGUAGES = {
  en: {
    navDashboard: 'Dashboard',
    navInfo: 'PD Information',
    navPatient: 'Patient Profile',
    navVoice: 'Speech Assessment',
    navTremor: 'Tremor Assessment',
    navGait: 'Gait Assessment',
    navFacial: 'Facial Expression',
    navQuestions: 'Questions',
    navSpiral: 'Spiral Drawing',
    navResults: 'Results',
    navReport: 'Report',
    
    dashboardTitle: 'Dashboard',
    dashboardDesc: 'Clinical Assessment Overview',
    noPatientText: 'No patient information',
    voiceBoxTitle: 'Speech',
    voiceStatus: 'Not started',
    tremorBoxTitle: 'Tremor',
    tremorStatus: 'Not started',
    gaitBoxTitle: 'Gait',
    gaitStatus: 'Not started',
    facialBoxTitle: 'Facial',
    facialStatus: 'Not started',
    questionsBoxTitle: 'Questions',
    questionsStatus: 'Not started',
    spiralBoxTitle: 'Spiral',
    spiralStatus: 'Not started',
    startBtn: 'Start Assessment',
    
    patientTitle: 'Patient Profile',
    patientDesc: 'Complete demographic information',
    labelFirstName: 'First Name',
    labelLastName: 'Last Name',
    labelDOB: 'Date of Birth',
    labelGender: 'Gender',
    labelCountry: 'Country',
    labelPhone: 'Phone',
    labelEmail: 'Email',
    labelMedicalId: 'Medical Record ID',
    optMale: 'Male',
    optFemale: 'Female',
    optOther: 'Other',
    savePatientBtn: 'Save Profile',
    
    infoTitle: 'Parkinson\'s Disease Information',
    infoSubtitle: 'Clinical Background - MDS-UPDRS Part III',
    whatIsPDTitle: 'What is Parkinson\'s Disease?',
    whatIsPDText: 'Progressive neurodegenerative disorder characterized by tremor, bradykinesia, rigidity, and postural instability.',
    updrsTitle: 'MDS-UPDRS Part III Scoring',
    scoreHeader: 'Score',
    severityHeader: 'Severity',
    sev0: 'Normal',
    sev1: 'Slight',
    sev2: 'Mild',
    sev3: 'Moderate',
    sev4: 'Severe',
    
    voiceTitle: 'Speech Assessment',
    voiceDesc: 'Record 3 trials of sustained AAAAA (6 seconds each)',
    voiceInstructions: 'You will record 3 trials. Click below to start.',
    startVoiceBtn: 'Start Recording',
    countdownText: 'Starting in...',
    recordingText: 'Recording...',
    trialResultsTitle: 'Trial Results',
    jitterLabel: 'Jitter (%)',
    shimmerLabel: 'Shimmer (dB)',
    hnrLabel: 'HNR (dB)',
    f0Label: 'F0 (Hz)',
    voiceNextBtn: 'Next Trial',
    voiceCompleteBtn: 'Complete Test',
    
    tremorTitle: 'Tremor Assessment',
    tremorDesc: 'Hold device steady for 10 seconds',
    tremorInstructions: 'Select which hand to test',
    leftHandBtn: 'Left Hand',
    rightHandBtn: 'Right Hand',
    tremorCountText: 'Starting in...',
    tremorRecText: 'Recording...',
    tremorMetricsTitle: 'Tremor Metrics',
    frequencyLabel: 'Frequency (Hz)',
    amplitudeLabel: 'Amplitude (mg)',
    powerLabel: 'Power (dB)',
    tremorCompleteBtn: 'Complete Test',
    
    gaitTitle: 'Gait Assessment',
    gaitDesc: 'Camera-based gait analysis (15 seconds)',
    gaitInstructions: 'Position yourself in frame and click to start.',
    startGaitBtn: 'Start Camera',
    gaitRecText: 'Analyzing...',
    cadenceLabel: 'Cadence (steps/min)',
    strideLabel: 'Stride Length (m)',
    speedLabel: 'Speed (m/s)',
    gaitCompleteBtn: 'Complete Test',
    
    facialTitle: 'Facial Expression Assessment',
    facialDesc: 'Camera-based facial analysis (10 seconds)',
    facialInstructions: 'Position your face in frame and click to start.',
    startFacialBtn: 'Start Camera',
    facialRecText: 'Analyzing...',
    blinkLabel: 'Blink Rate (/min)',
    jawLabel: 'Jaw Opening (cm)',
    mouthLabel: 'Mouth Width (cm)',
    facialCompleteBtn: 'Complete Test',
    
    questionsTitle: 'Questions Assessment',
    q1Label: '1. Do you experience slowness of movement (bradykinesia)?',
    q2Label: '2. Do you have stiffness/rigidity in arms or legs?',
    q3Label: '3. Do you have balance issues or near falls?',
    q1No: 'No',
    q1Sometimes: 'Sometimes',
    q1Often: 'Often',
    q1Always: 'Always',
    q2No: 'No',
    q2Sometimes: 'Sometimes',
    q2Often: 'Often',
    q2Always: 'Always',
    q3No: 'No',
    q3Sometimes: 'Sometimes',
    q3Often: 'Often',
    q3Always: 'Always',
    submitQuestionsBtn: 'Save Answers',
    
    spiralTitle: 'Spiral Drawing Test',
    spiralDesc: 'Draw a smooth spiral using your finger/stylus',
    refSpiralTitle: 'Reference',
    yourSpiralTitle: 'Your Drawing',
    clearBtn: 'Clear',
    tremorIndexLabel: 'Tremor Index',
    pathLengthLabel: 'Path Length (px)',
    velocityLabel: 'Velocity (px/s)',
    calcSpiralBtn: 'Calculate Metrics',
    spiralCompleteBtn: 'Complete Test',
    
    resultsTitleAssessment: 'Assessment Results',
    resultsDesc: 'Complete MDS-UPDRS Summary',
    domainHeader: 'Domain',
    scoreHeader2: 'Score (0-4)',
    severityHeader2: 'Severity',
    generateReportBtn: 'Generate Report',
    
    reportTitle: 'Clinical Report',
    patientInfoTitle: 'Patient Information',
    rptNameLabel: 'Name',
    rptAgeLabel: 'Age',
    rptGenderLabel: 'Gender',
    rptCountryLabel: 'Country',
    rptEmailLabel: 'Email',
    assessmentSummaryTitle: 'Assessment Summary',
    rptVoiceSevLabel: 'Speech Severity',
    rptTremorSevLabel: 'Tremor Severity',
    rptGaitSevLabel: 'Gait Severity',
    rptFacialSevLabel: 'Facial Severity',
    rptCogSevLabel: 'Cognitive Severity',
    rptCoordSevLabel: 'Coordination Severity',
    disclaimerNote: '<strong>Clinical Disclaimer:</strong> This is a research screening tool. Always consult with a qualified clinician for diagnosis and treatment decisions.',
    downloadPDFBtn: 'Download PDF Report',
    
    sidebarTitle: 'Navigation',
    disclaimerText: 'Research prototype only',
  },

  hi: {
    navDashboard: 'डैशबोर्ड',
    navInfo: 'पार्किंसंस रोग जानकारी',
    navPatient: 'रोगी प्रोफाइल',
    navVoice: 'भाषण मूल्यांकन',
    navTremor: 'कंपन मूल्यांकन',
    navGait: 'चाल मूल्यांकन',
    navFacial: 'चेहरा की अभिव्यक्ति',
    navQuestions: 'प्रश्न',
    navSpiral: 'सर्पिल ड्राइंग',
    navResults: 'परिणाम',
    navReport: 'रिपोर्ट',
    
    dashboardTitle: 'डैशबोर्ड',
    dashboardDesc: 'नैदानिक मूल्यांकन अवलोकन',
    noPatientText: 'कोई रोगी जानकारी नहीं',
    voiceBoxTitle: 'भाषण',
    voiceStatus: 'शुरू नहीं हुआ',
    tremorBoxTitle: 'कंपन',
    tremorStatus: 'शुरू नहीं हुआ',
    gaitBoxTitle: 'चाल',
    gaitStatus: 'शुरू नहीं हुआ',
    facialBoxTitle: 'चेहरा',
    facialStatus: 'शुरू नहीं हुआ',
    questionsBoxTitle: 'प्रश्न',
    questionsStatus: 'शुरू नहीं हुआ',
    spiralBoxTitle: 'सर्पिल',
    spiralStatus: 'शुरू नहीं हुआ',
    startBtn: 'मूल्यांकन शुरू करें',
    
    patientTitle: 'रोगी प्रोफाइल',
    patientDesc: 'पूर्ण जनसांख्यिकी जानकारी',
    labelFirstName: 'पहला नाम',
    labelLastName: 'अंतिम नाम',
    labelDOB: 'जन्मतिथि',
    labelGender: 'लिंग',
    labelCountry: 'देश',
    labelPhone: 'फोन',
    labelEmail: 'ईमेल',
    labelMedicalId: 'चिकित्सा रिकॉर्ड ID',
    optMale: 'पुरुष',
    optFemale: 'महिला',
    optOther: 'अन्य',
    savePatientBtn: 'प्रोफाइल सहेजें',
    
    infoTitle: 'पार्किंसंस रोग की जानकारी',
    infoSubtitle: 'नैदानिक पृष्ठभूमि - MDS-UPDRS भाग III',
    whatIsPDTitle: 'पार्किंसंस रोग क्या है?',
    whatIsPDText: 'प्रगतिशील न्यूरोडीजेनेरेटिव विकार कंपन, ब्रैडीकिनेसिया, कठोरता और मुद्रात्मक अस्थिरता की विशेषता है।',
    updrsTitle: 'MDS-UPDRS भाग III स्कोरिंग',
    scoreHeader: 'स्कोर',
    severityHeader: 'गंभीरता',
    sev0: 'सामान्य',
    sev1: 'मामूली',
    sev2: 'हल्का',
    sev3: 'मध्यम',
    sev4: 'गंभीर',
    
    voiceTitle: 'भाषण मूल्यांकन',
    voiceDesc: 'AAAAA के 3 ट्रायल रिकॉर्ड करें (प्रत्येक 6 सेकंड)',
    voiceInstructions: 'आप 3 ट्रायल रिकॉर्ड करेंगे। शुरू करने के लिए नीचे क्लिक करें।',
    startVoiceBtn: 'रिकॉर्डिंग शुरू करें',
    countdownText: 'शुरुआत में...',
    recordingText: 'रिकॉर्डिंग...',
    trialResultsTitle: 'ट्रायल परिणाम',
    jitterLabel: 'जिटर (%)',
    shimmerLabel: 'शिमर (dB)',
    hnrLabel: 'HNR (dB)',
    f0Label: 'F0 (Hz)',
    voiceNextBtn: 'अगला ट्रायल',
    voiceCompleteBtn: 'परीक्षण पूर्ण करें',
    
    tremorTitle: 'कंपन मूल्यांकन',
    tremorDesc: 'डिवाइस को 10 सेकंड के लिए स्थिर रखें',
    tremorInstructions: 'परीक्षण के लिए कौन सा हाथ चुनें',
    leftHandBtn: 'बाएं हाथ',
    rightHandBtn: 'दाएं हाथ',
    tremorCountText: 'शुरुआत में...',
    tremorRecText: 'रिकॉर्डिंग...',
    tremorMetricsTitle: 'कंपन मेट्रिक्स',
    frequencyLabel: 'आवृत्ति (Hz)',
    amplitudeLabel: 'आयाम (mg)',
    powerLabel: 'शक्ति (dB)',
    tremorCompleteBtn: 'परीक्षण पूर्ण करें',
    
    gaitTitle: 'चाल मूल्यांकन',
    gaitDesc: 'कैमरा-आधारित चाल विश्लेषण (15 सेकंड)',
    gaitInstructions: 'स्वयं को फ्रेम में रखें और शुरू करने के लिए क्लिक करें।',
    startGaitBtn: 'कैमरा शुरू करें',
    gaitRecText: 'विश्लेषण...',
    cadenceLabel: 'केडेंस (कदम/मिनट)',
    strideLabel: 'स्ट्राइड लंबाई (m)',
    speedLabel: 'गति (m/s)',
    gaitCompleteBtn: 'परीक्षण पूर्ण करें',
    
    facialTitle: 'चेहरे की अभिव्यक्ति मूल्यांकन',
    facialDesc: 'कैमरा-आधारित चेहरे का विश्लेषण (10 सेकंड)',
    facialInstructions: 'अपने चेहरे को फ्रेम में रखें और शुरू करने के लिए क्लिक करें।',
    startFacialBtn: 'कैमरा शुरू करें',
    facialRecText: 'विश्लेषण...',
    blinkLabel: 'पलक दर (/मिनट)',
    jawLabel: 'जबड़े का खुलना (cm)',
    mouthLabel: 'मुंह की चौड़ाई (cm)',
    facialCompleteBtn: 'परीक्षण पूर्ण करें',
    
    questionsTitle: 'प्रश्न मूल्यांकन',
    q1Label: '1. क्या आप आंदोलन की गतिमंदता (ब्रैडीकिनेसिया) का अनुभव करते हैं?',
    q2Label: '2. क्या आपके पास बांहों या पैरों में कठोरता/कठोरता है?',
    q3Label: '3. क्या आपको संतुलन समस्याएं या लगभग गिरावट आती हैं?',
    q1No: 'नहीं',
    q1Sometimes: 'कभी कभी',
    q1Often: 'अक्सर',
    q1Always: 'हमेशा',
    q2No: 'नहीं',
    q2Sometimes: 'कभी कभी',
    q2Often: 'अक्सर',
    q2Always: 'हमेशा',
    q3No: 'नहीं',
    q3Sometimes: 'कभी कभी',
    q3Often: 'अक्सर',
    q3Always: 'हमेशा',
    submitQuestionsBtn: 'उत्तर सहेजें',
    
    spiralTitle: 'सर्पिल ड्राइंग परीक्षण',
    spiralDesc: 'अपनी उंगली/स्टाइलस का उपयोग करके एक चिकनी सर्पिल बनाएं',
    refSpiralTitle: 'संदर्भ',
    yourSpiralTitle: 'आपकी ड्राइंग',
    clearBtn: 'साफ करें',
    tremorIndexLabel: 'कंपन सूचकांक',
    pathLengthLabel: 'पथ लंबाई (px)',
    velocityLabel: 'वेग (px/s)',
    calcSpiralBtn: 'मेट्रिक्स की गणना करें',
    spiralCompleteBtn: 'परीक्षण पूर्ण करें',
    
    resultsTitleAssessment: 'मूल्यांकन परिणाम',
    resultsDesc: 'पूर्ण MDS-UPDRS सारांश',
    domainHeader: 'डोमेन',
    scoreHeader2: 'स्कोर (0-4)',
    severityHeader2: 'गंभीरता',
    generateReportBtn: 'रिपोर्ट उत्पन्न करें',
    
    reportTitle: 'नैदानिक रिपोर्ट',
    patientInfoTitle: 'रोगी जानकारी',
    rptNameLabel: 'नाम',
    rptAgeLabel: 'उम्र',
    rptGenderLabel: 'लिंग',
    rptCountryLabel: 'देश',
    rptEmailLabel: 'ईमेल',
    assessmentSummaryTitle: 'मूल्यांकन सारांश',
    rptVoiceSevLabel: 'भाषण गंभीरता',
    rptTremorSevLabel: 'कंपन गंभीरता',
    rptGaitSevLabel: 'चाल गंभीरता',
    rptFacialSevLabel: 'चेहरे की गंभीरता',
    rptCogSevLabel: 'संज्ञानात्मक गंभीरता',
    rptCoordSevLabel: 'समन्वय गंभीरता',
    disclaimerNote: '<strong>नैदानिक अस्वीकरण:</strong> यह एक अनुसंधान स्क्रीनिंग उपकरण है। निदान और उपचार निर्णय के लिए हमेशा एक योग्य चिकित्सक से परामर्श लें।',
    downloadPDFBtn: 'PDF रिपोर्ट डाउनलोड करें',
    
    sidebarTitle: 'नेविगेशन',
    disclaimerText: 'शोध प्रोटोटाइप केवल',
  },

  ru: {
    navDashboard: 'Панель',
    navInfo: 'Информация о болезни Паркинсона',
    navPatient: 'Профиль пациента',
    navVoice: 'Оценка речи',
    navTremor: 'Оценка тремора',
    navGait: 'Оценка походки',
    navFacial: 'Выражение лица',
    navQuestions: 'Вопросы',
    navSpiral: 'Спираль рисования',
    navResults: 'Результаты',
    navReport: 'Отчет',
    
    dashboardTitle: 'Панель',
    dashboardDesc: 'Обзор клинической оценки',
    noPatientText: 'Нет информации о пациенте',
    voiceBoxTitle: 'Речь',
    voiceStatus: 'Не начато',
    tremorBoxTitle: 'Тремор',
    tremorStatus: 'Не начато',
    gaitBoxTitle: 'Походка',
    gaitStatus: 'Не начато',
    facialBoxTitle: 'Лицо',
    facialStatus: 'Не начато',
    questionsBoxTitle: 'Вопросы',
    questionsStatus: 'Не начато',
    spiralBoxTitle: 'Спираль',
    spiralStatus: 'Не начато',
    startBtn: 'Начать оценку',
    
    patientTitle: 'Профиль пациента',
    patientDesc: 'Полная демографическая информация',
    labelFirstName: 'Имя',
    labelLastName: 'Фамилия',
    labelDOB: 'Дата рождения',
    labelGender: 'Пол',
    labelCountry: 'Страна',
    labelPhone: 'Телефон',
    labelEmail: 'Электронная почта',
    labelMedicalId: 'ID медицинской карты',
    optMale: 'Мужской',
    optFemale: 'Женский',
    optOther: 'Другое',
    savePatientBtn: 'Сохранить профиль',
    
    infoTitle: 'Информация о болезни Паркинсона',
    infoSubtitle: 'Клиническая справка - MDS-UPDRS часть III',
    whatIsPDTitle: 'Что такое болезнь Паркинсона?',
    whatIsPDText: 'Прогрессирующее нейродегенеративное расстройство, характеризующееся тремором, брадикинезией, ригидностью и постуральной нестабильностью.',
    updrsTitle: 'MDS-UPDRS Часть III Оценка',
    scoreHeader: 'Оценка',
    severityHeader: 'Тяжесть',
    sev0: 'Нормальный',
    sev1: 'Легкий',
    sev2: 'Слабый',
    sev3: 'Умеренный',
    sev4: 'Тяжелый',
    
    voiceTitle: 'Оценка речи',
    voiceDesc: 'Запишите 3 попытки устойчивой ААААА (по 6 секунд каждая)',
    voiceInstructions: 'Вы будете записывать 3 попытки. Нажмите ниже, чтобы начать.',
    startVoiceBtn: 'Начать запись',
    countdownText: 'Начиная с...',
    recordingText: 'Запись...',
    trialResultsTitle: 'Результаты испытания',
    jitterLabel: 'Джиттер (%)',
    shimmerLabel: 'Шиммер (дБ)',
    hnrLabel: 'HNR (дБ)',
    f0Label: 'F0 (Hz)',
    voiceNextBtn: 'Следующая попытка',
    voiceCompleteBtn: 'Завершить тест',
    
    tremorTitle: 'Оценка тремора',
    tremorDesc: 'Держите устройство неподвижно в течение 10 секунд',
    tremorInstructions: 'Выберите, какую руку тестировать',
    leftHandBtn: 'Левая рука',
    rightHandBtn: 'Правая рука',
    tremorCountText: 'Начиная с...',
    tremorRecText: 'Запись...',
    tremorMetricsTitle: 'Метрики тремора',
    frequencyLabel: 'Частота (Hz)',
    amplitudeLabel: 'Амплитуда (мг)',
    powerLabel: 'Мощность (дБ)',
    tremorCompleteBtn: 'Завершить тест',
    
    gaitTitle: 'Оценка походки',
    gaitDesc: 'Анализ походки на основе камеры (15 секунд)',
    gaitInstructions: 'Поместите себя в кадр и нажмите, чтобы начать.',
    startGaitBtn: 'Запустить камеру',
    gaitRecText: 'Анализ...',
    cadenceLabel: 'Кадам (шагов/мин)',
    strideLabel: 'Длина шага (м)',
    speedLabel: 'Скорость (м/с)',
    gaitCompleteBtn: 'Завершить тест',
    
    facialTitle: 'Оценка выражения лица',
    facialDesc: 'Анализ лица на основе камеры (10 секунд)',
    facialInstructions: 'Поместите лицо в кадр и нажмите, чтобы начать.',
    startFacialBtn: 'Запустить камеру',
    facialRecText: 'Анализ...',
    blinkLabel: 'Частота морганий (/мин)',
    jawLabel: 'Открытие челюсти (см)',
    mouthLabel: 'Ширина рта (см)',
    facialCompleteBtn: 'Завершить тест',
    
    questionsTitle: 'Оценка вопросов',
    q1Label: '1. Вы испытываете замедление движений (брадикинезию)?',
    q2Label: '2. У вас есть скованность/жесткость в руках или ногах?',
    q3Label: '3. Вы испытываете проблемы с равновесием или падения?',
    q1No: 'Нет',
    q1Sometimes: 'Иногда',
    q1Often: 'Часто',
    q1Always: 'Всегда',
    q2No: 'Нет',
    q2Sometimes: 'Иногда',
    q2Often: 'Часто',
    q2Always: 'Всегда',
    q3No: 'Нет',
    q3Sometimes: 'Иногда',
    q3Often: 'Часто',
    q3Always: 'Всегда',
    submitQuestionsBtn: 'Сохранить ответы',
    
    spiralTitle: 'Тест спирали рисования',
    spiralDesc: 'Нарисуйте гладкую спираль, используя палец/стилус',
    refSpiralTitle: 'Справка',
    yourSpiralTitle: 'Ваш рисунок',
    clearBtn: 'Очистить',
    tremorIndexLabel: 'Индекс тремора',
    pathLengthLabel: 'Длина пути (px)',
    velocityLabel: 'Скорость (px/s)',
    calcSpiralBtn: 'Рассчитать метрики',
    spiralCompleteBtn: 'Завершить тест',
    
    resultsTitleAssessment: 'Результаты оценки',
    resultsDesc: 'Полная сводка MDS-UPDRS',
    domainHeader: 'Домен',
    scoreHeader2: 'Оценка (0-4)',
    severityHeader2: 'Тяжесть',
    generateReportBtn: 'Создать отчет',
    
    reportTitle: 'Клинический отчет',
    patientInfoTitle: 'Информация о пациенте',
    rptNameLabel: 'Имя',
    rptAgeLabel: 'Возраст',
    rptGenderLabel: 'Пол',
    rptCountryLabel: 'Страна',
    rptEmailLabel: 'Электронная почта',
    assessmentSummaryTitle: 'Сводка оценки',
    rptVoiceSevLabel: 'Тяжесть речи',
    rptTremorSevLabel: 'Тяжесть тремора',
    rptGaitSevLabel: 'Тяжесть походки',
    rptFacialSevLabel: 'Тяжесть лица',
    rptCogSevLabel: 'Когнитивная тяжесть',
    rptCoordSevLabel: 'Тяжесть координации',
    disclaimerNote: '<strong>Клинический отказ от ответственности:</strong> Это инструмент исследовательского скрининга. Всегда консультируйтесь с квалифицированным врачом для принятия решений о диагностике и лечении.',
    downloadPDFBtn: 'Скачать PDF отчет',
    
    sidebarTitle: 'Навигация',
    disclaimerText: 'Только исследовательский прототип',
  },

  kg: {
    navDashboard: 'Панель',
    navInfo: 'Паркинсон аурусу',
    navPatient: 'Пациенттин профили',
    navVoice: 'Сөз баалоо',
    navTremor: 'Титирөө баалоо',
    navGait: 'Жүрүштүн баалоосу',
    navFacial: 'Жүзүнүн туюнтмасы',
    navQuestions: 'Суроолор',
    navSpiral: 'Спираль чиймелөө',
    navResults: 'Жыйынтыктар',
    navReport: 'Отчет',
    
    dashboardTitle: 'Панель',
    dashboardDesc: 'Клиникалык баалоонун сынамасы',
    noPatientText: 'Пациенттин маалыматы жок',
    voiceBoxTitle: 'Сөз',
    voiceStatus: 'Баштала элек',
    tremorBoxTitle: 'Титирөө',
    tremorStatus: 'Баштала элек',
    gaitBoxTitle: 'Жүрүш',
    gaitStatus: 'Баштала элек',
    facialBoxTitle: 'Жүз',
    facialStatus: 'Баштала элек',
    questionsBoxTitle: 'Суроолор',
    questionsStatus: 'Баштала элек',
    spiralBoxTitle: 'Спираль',
    spiralStatus: 'Баштала элек',
    startBtn: 'Баалоону баштоо',
    
    patientTitle: 'Пациенттин профили',
    patientDesc: 'Толук демографиялык маалымат',
    labelFirstName: 'Аты',
    labelLastName: 'Фамилиясы',
    labelDOB: 'Туулган датасы',
    labelGender: 'Жынысы',
    labelCountry: 'Өлкө',
    labelPhone: 'Телефон',
    labelEmail: 'Электрондук почта',
    labelMedicalId: 'Медициналык каттап ID',
    optMale: 'Эр',
    optFemale: 'Ж',
    optOther: 'Башка',
    savePatientBtn: 'Профилди сактоо',
    
    infoTitle: 'Паркинсон аурусу маалыматы',
    infoSubtitle: 'Клиникалык негиз - MDS-UPDRS III бөлүмү',
    whatIsPDTitle: 'Паркинсон аурусу деген эмне?',
    whatIsPDText: 'Титирөө, брадикинезия, катуулук жана позициялык туруштук менен мүнөздөлгөн прогрессивдүү нейродегенеративдүү ооруу.',
    updrsTitle: 'MDS-UPDRS III бөлүмүнүн баллары',
    scoreHeader: 'Балл',
    severityHeader: 'Ауырлыгы',
    sev0: 'Нормалдуу',
    sev1: 'Жеңил',
    sev2: 'Бир аз',
    sev3: 'Орточо',
    sev4: 'Ауыр',
    
    voiceTitle: 'Сөз баалоо',
    voiceDesc: '3 сынаманы жазыңыз (ар бири 6 секунд)',
    voiceInstructions: 'Сиз 3 сынама жазасыз. Баштоо үчүн төмөнкүнү басыңыз.',
    startVoiceBtn: 'Жазууну баштоо',
    countdownText: 'Баштап...',
    recordingText: 'Жазуу...',
    trialResultsTitle: 'Сынама натыйжасы',
    jitterLabel: 'Титирөө (%)',
    shimmerLabel: 'Чагылдыруу (дБ)',
    hnrLabel: 'HNR (дБ)',
    f0Label: 'F0 (Hz)',
    voiceNextBtn: 'Кийинки сынама',
    voiceCompleteBtn: 'Тестти аяктоо',
    
    tremorTitle: 'Титирөө баалоо',
    tremorDesc: 'Аппаратты 10 секунд туруктуу кармап туруңуз',
    tremorInstructions: 'Кайсы колду сынаганы чечиңиз',
    leftHandBtn: 'Сол колу',
    rightHandBtn: 'Оң колу',
    tremorCountText: 'Баштап...',
    tremorRecText: 'Жазуу...',
    tremorMetricsTitle: 'Титирөө өлчөмдөрү',
    frequencyLabel: 'Жыштыгы (Hz)',
    amplitudeLabel: 'Амплитудасы (мг)',
    powerLabel: 'Күчү (дБ)',
    tremorCompleteBtn: 'Тестти аяктоо',
    
    gaitTitle: 'Жүрүштүн баалоосу',
    gaitDesc: 'Камерага негизделген жүрүш анализи (15 секунд)',
    gaitInstructions: 'Өзүңүздү кадрга коюңуз жана баштоо үчүн басыңыз.',
    startGaitBtn: 'Камераны баштоо',
    gaitRecText: 'Талдоо...',
    cadenceLabel: 'Ритм (кадам/мин)',
    strideLabel: 'Кадамдын узундугу (м)',
    speedLabel: 'Ылдамдыгы (м/с)',
    gaitCompleteBtn: 'Тестти аяктоо',
    
    facialTitle: 'Жүзүнүн туюнтмасын баалоо',
    facialDesc: 'Камерага негизделген жүз анализи (10 секунд)',
    facialInstructions: 'Жүзүңүздү кадрга коюңуз жана баштоо үчүн басыңыз.',
    startFacialBtn: 'Камераны баштоо',
    facialRecText: 'Талдоо...',
    blinkLabel: 'Жымыруу ылдамдыгы (/мин)',
    jawLabel: 'Ичке ачылышы (см)',
    mouthLabel: 'Ооздун туурасы (см)',
    facialCompleteBtn: 'Тестти аяктоо',
    
    questionsTitle: 'Суроолор баалоосу',
    q1Label: '1. Кыймылдын жайлыгын сезесизби (брадикинезия)?',
    q2Label: '2. Колунузда же буттарында катуулук/катуулук барбы?',
    q3Label: '3. Тең салмактуулук көйгөйлөрү же түшүүлөр байкадыңызбы?',
    q1No: 'Жок',
    q1Sometimes: 'Кээде',
    q1Often: 'Көбүнчө',
    q1Always: 'Дайыма',
    q2No: 'Жок',
    q2Sometimes: 'Кээде',
    q2Often: 'Көбүнчө',
    q2Always: 'Дайыма',
    q3No: 'Жок',
    q3Sometimes: 'Кээде',
    q3Often: 'Көбүнчө',
    q3Always: 'Дайыма',
    submitQuestionsBtn: 'Жооптарды сактоо',
    
    spiralTitle: 'Спираль чиймелөө тести',
    spiralDesc: 'Саламатмасы/стилус колу менен жылмакай спираль чиймелөөңүз',
    refSpiralTitle: 'Чиймеме',
    yourSpiralTitle: 'Сизин чиймеңиз',
    clearBtn: 'Тазалоо',
    tremorIndexLabel: 'Титирөө индекси',
    pathLengthLabel: 'Жолдун узундугу (px)',
    velocityLabel: 'Ылдамдыгы (px/s)',
    calcSpiralBtn: 'Өлчөмдөрдү эсептөө',
    spiralCompleteBtn: 'Тестти аяктоо',
    
    resultsTitleAssessment: 'Баалоо жыйынтыктары',
    resultsDesc: 'Толук MDS-UPDRS резюме',
    domainHeader: 'Домен',
    scoreHeader2: 'Балл (0-4)',
    severityHeader2: 'Ауырлыгы',
    generateReportBtn: 'Отчетту түзүү',
    
    reportTitle: 'Клиникалык отчет',
    patientInfoTitle: 'Пациенттин маалыматы',
    rptNameLabel: 'Аты',
    rptAgeLabel: 'Жашы',
    rptGenderLabel: 'Жынысы',
    rptCountryLabel: 'Өлкө',
    rptEmailLabel: 'Электрондук почта',
    assessmentSummaryTitle: 'Баалоонун жыйынтыгы',
    rptVoiceSevLabel: 'Сөзүн ауырлыгы',
    rptTremorSevLabel: 'Титирөөнүн ауырлыгы',
    rptGaitSevLabel: 'Жүрүштүн ауырлыгы',
    rptFacialSevLabel: 'Жүзүнүн ауырлыгы',
    rptCogSevLabel: 'Когнитивдүү ауырлыгы',
    rptCoordSevLabel: 'Координация ауырлыгы',
    disclaimerNote: '<strong>Клиникалык чектеме:</strong> Бул изилдөө экранындагы аспап. Диагноз жана дарылоо чечимдери үчүн дайыма квалификациялуу дарыгерге кайрылыңыз.',
    downloadPDFBtn: 'PDF отчетун жүктөп алуу',
    
    sidebarTitle: 'Навигация',
    disclaimerText: 'Изилдөө прототипи гана',
  },

  kz: {
    navDashboard: 'Панель',
    navInfo: 'Паркинсон ауырының ақпараты',
    navPatient: 'Пациенттің профилі',
    navVoice: 'Сөйлеу бағалау',
    navTremor: 'Дрожь бағалау',
    navGait: 'Жүру бағалау',
    navFacial: 'Бет өрнегі',
    navQuestions: 'Сұрақтар',
    navSpiral: 'Спираль сызу',
    navResults: 'Нәтижелер',
    navReport: 'Есеп',
    
    dashboardTitle: 'Панель',
    dashboardDesc: 'Клиникалық бағалаудың шолуы',
    noPatientText: 'Пациенттің ақпараты жоқ',
    voiceBoxTitle: 'Сөйлеу',
    voiceStatus: 'Басталмады',
    tremorBoxTitle: 'Дрожь',
    tremorStatus: 'Басталмады',
    gaitBoxTitle: 'Жүру',
    gaitStatus: 'Басталмады',
    facialBoxTitle: 'Бет',
    facialStatus: 'Басталмады',
    questionsBoxTitle: 'Сұрақтар',
    questionsStatus: 'Басталмады',
    spiralBoxTitle: 'Спираль',
    spiralStatus: 'Басталмады',
    startBtn: 'Бағалауды бастау',
    
    patientTitle: 'Пациенттің профилі',
    patientDesc: 'Толық демографиялық ақпарат',
    labelFirstName: 'Аты',
    labelLastName: 'Фамилиясы',
    labelDOB: 'Туғылған күні',
    labelGender: 'Жынысы',
    labelCountry: 'Ел',
    labelPhone: 'Телефон',
    labelEmail: 'Электрондық пошта',
    labelMedicalId: 'Медициналық құжат ID',
    optMale: 'Ер',
    optFemale: 'Әйел',
    optOther: 'Басқа',
    savePatientBtn: 'Профильді сақтау',
    
    infoTitle: 'Паркинсон ауырының ақпараты',
    infoSubtitle: 'Клиникалық негіз - MDS-UPDRS III бөлімі',
    whatIsPDTitle: 'Паркинсон ауырығы дегеніміз не?',
    whatIsPDText: 'Дрожь, брадикинезия, қатаңдық және күйік нестабильлігімен сипатталатын прогрессивтіөндіктің дамуы.',
    updrsTitle: 'MDS-UPDRS III бөлімінің баллары',
    scoreHeader: 'Балл',
    severityHeader: 'Ауырлығы',
    sev0: 'Қалыпты',
    sev1: 'Аз',
    sev2: 'Салқын',
    sev3: 'Орташа',
    sev4: 'Ауыр',
    
    voiceTitle: 'Сөйлеу бағалау',
    voiceDesc: '3 сынаманы жазыңыз (әрқайсысы 6 секунд)',
    voiceInstructions: 'Сіз 3 сынама жазасыз. Басту үшін төмендегісін басыңыз.',
    startVoiceBtn: 'Жазуды бастау',
    countdownText: 'Басталып...',
    recordingText: 'Жазу...',
    trialResultsTitle: 'Сынама нәтижелері',
    jitterLabel: 'Дрожь (%)',
    shimmerLabel: 'Шіңбіру (дБ)',
    hnrLabel: 'HNR (дБ)',
    f0Label: 'F0 (Hz)',
    voiceNextBtn: 'Келесі сынама',
    voiceCompleteBtn: 'Тестті аяқтау',
    
    tremorTitle: 'Дрожь бағалау',
    tremorDesc: 'Құрылғыны 10 секунд ұстап туруңыз',
    tremorInstructions: 'Қай қолды сынау керектігін таңдаңыз',
    leftHandBtn: 'Сол қол',
    rightHandBtn: 'Оң қол',
    tremorCountText: 'Басталып...',
    tremorRecText: 'Жазу...',
    tremorMetricsTitle: 'Дрожь өлшемдері',
    frequencyLabel: 'Жиілігі (Hz)',
    amplitudeLabel: 'Амплитудасы (мг)',
    powerLabel: 'Қуаты (дБ)',
    tremorCompleteBtn: 'Тестті аяқтау',
    
    gaitTitle: 'Жүру бағалау',
    gaitDesc: 'Камераға негіз бойынша жүру анализі (15 секунд)',
    gaitInstructions: 'Өзіңізді кадрға коюңыз және басту үшін басыңыз.',
    startGaitBtn: 'Камераны іске қосу',
    gaitRecText: 'Талдау...',
    cadenceLabel: 'Қадам (қадам/мин)',
    strideLabel: 'Қадам ұзындығы (м)',
    speedLabel: 'Жылдамдығы (м/с)',
    gaitCompleteBtn: 'Тестті аяқтау',
    
    facialTitle: 'Бет өрнегін бағалау',
    facialDesc: 'Камераға негіз бойынша бет талдауы (10 секунд)',
    facialInstructions: 'Беттіңізді кадрға коюңыз және басту үшін басыңыз.',
    startFacialBtn: 'Камераны іске қосу',
    facialRecText: 'Талдау...',
    blinkLabel: 'Көзік жылдамдығы (/мин)',
    jawLabel: 'Ағызын ашуы (см)',
    mouthLabel: 'Ауыздың ені (см)',
    facialCompleteBtn: 'Тестті аяқтау',
    
    questionsTitle: 'Сұрақтарды бағалау',
    q1Label: '1. Қозғалыс ынамсыздығын (брадикинезияны) сезесіз бе?',
    q2Label: '2. Қолыңызда немесе аяқтарында қаттаңдық/қатаңдық барма?',
    q3Label: '3. Теңдеу мәселесі немесе түспейтін болуларың байқадыңыз ба?',
    q1No: 'Жоқ',
    q1Sometimes: 'Кейде',
    q1Often: 'Көп',
    q1Always: 'Әрқашан',
    q2No: 'Жоқ',
    q2Sometimes: 'Кейде',
    q2Often: 'Көп',
    q2Always: 'Әрқашан',
    q3No: 'Жоқ',
    q3Sometimes: 'Кейде',
    q3Often: 'Көп',
    q3Always: 'Әрқашан',
    submitQuestionsBtn: 'Жауаптарды сақтау',
    
    spiralTitle: 'Спираль сызу тесті',
    spiralDesc: 'Пармақ/стилус арқылы тегіс спираль сызыңыз',
    refSpiralTitle: 'Сылғылау',
    yourSpiralTitle: 'Сіздің сызығыңыз',
    clearBtn: 'Тазалау',
    tremorIndexLabel: 'Дрожь индексі',
    pathLengthLabel: 'Жолдың ұзындығы (px)',
    velocityLabel: 'Жылдамдығы (px/s)',
    calcSpiralBtn: 'Өлшемдерді есептеу',
    spiralCompleteBtn: 'Тестті аяқтау',
    
    resultsTitleAssessment: 'Бағалаудың нәтижелері',
    resultsDesc: 'Толық MDS-UPDRS резюме',
    domainHeader: 'Домен',
    scoreHeader2: 'Балл (0-4)',
    severityHeader2: 'Ауырлығы',
    generateReportBtn: 'Есеп құру',
    
    reportTitle: 'Клиникалық есеп',
    patientInfoTitle: 'Пациенттің ақпараты',
    rptNameLabel: 'Аты',
    rptAgeLabel: 'Жасы',
    rptGenderLabel: 'Жынысы',
    rptCountryLabel: 'Ел',
    rptEmailLabel: 'Электрондық пошта',
    assessmentSummaryTitle: 'Бағалау қорытындысы',
    rptVoiceSevLabel: 'Сөйлеудің ауырлығы',
    rptTremorSevLabel: 'Дрожьтің ауырлығы',
    rptGaitSevLabel: 'Жүрудің ауырлығы',
    rptFacialSevLabel: 'Беттің ауырлығы',
    rptCogSevLabel: 'Танымдық ауырлығы',
    rptCoordSevLabel: 'Координация ауырлығы',
    disclaimerNote: '<strong>Клиникалық ескерту:</strong> Бұл ғылыми соондау құралы. Диагноз және емдеу шешімдері үшін әрқашан білік берілген дәрігерге хабарласыңыз.',
    downloadPDFBtn: 'PDF есепті жүктеп алу',
    
    sidebarTitle: 'Навигация',
    disclaimerText: 'Тек зерттеу прототипі',
  },
};

// ========== LANGUAGE FUNCTIONS ==========
function updateLanguage() {
  const lang = LANGUAGES[currentLanguage];
  
  // Update all text elements
  document.querySelectorAll('[id]').forEach(element => {
    const key = element.id;
    if (lang[key]) {
      if (key === 'disclaimerNote') {
        element.innerHTML = lang[key];
      } else {
        element.textContent = lang[key];
      }
    }
  });
  
  // Store preference
  localStorage.setItem('language', currentLanguage);
}

// ========== INITIALIZATION ==========
document.addEventListener('DOMContentLoaded', () => {
  // Load saved language preference
  const saved = localStorage.getItem('language');
  if (saved && LANGUAGES[saved]) {
    currentLanguage = saved;
    document.getElementById('languageSelector').value = saved;
  }
  
  updateLanguage();
});
